### ISSUE TITLE
Flaky-test: KafkaListenerNameTest

### ISSUE THREAD

**Issue by BewareMyPower** [streamnative/kop#1027]
KafkaListenerNameTest is flaky. All test method fails sporadically.

[example failure](https://github.com/streamnative/kop/runs/4870309444?check_suite_focus=true)

```
Error:  testListenerName(io.streamnative.pulsar.handlers.kop.KafkaListenerNameTest)  Time elapsed: 0.16 s  <<< FAILURE!
org.apache.pulsar.broker.PulsarServerException: java.io.IOException: Failed to bind Pulsar broker on /0.0.0.0:15002
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:783)
	at io.streamnative.pulsar.handlers.kop.KopProtocolHandlerTestBase.startBroker(KopProtocolHandlerTestBase.java:377)
	at io.streamnative.pulsar.handlers.kop.KopProtocolHandlerTestBase.startBroker(KopProtocolHandlerTestBase.java:368)
	at io.streamnative.pulsar.handlers.kop.KopProtocolHandlerTestBase.internalSetup(KopProtocolHandlerTestBase.java:284)
	at io.streamnative.pulsar.handlers.kop.KafkaListenerNameTest.testListenerName(KafkaListenerNameTest.java:143)

Error:  testMetadataRequestForMultiListeners(io.streamnative.pulsar.handlers.kop.KafkaListenerNameTest)  Time elapsed: 0.426 s  <<< FAILURE!
org.apache.pulsar.broker.PulsarServerException: java.io.IOException: Failed to bind Pulsar broker on /0.0.0.0:15002
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:783)
	at io.streamnative.pulsar.handlers.kop.KopProtocolHandlerTestBase.startBroker(KopProtocolHandlerTestBase.java:377)
	at io.streamnative.pulsar.handlers.kop.KopProtocolHandlerTestBase.startBroker(KopProtocolHandlerTestBase.java:368)
	at io.streamnative.pulsar.handlers.kop.KopProtocolHandlerTestBase.internalSetup(KopProtocolHandlerTestBase.java:284)
	at io.streamnative.pulsar.handlers.kop.KafkaListenerNameTest.testMetadataRequestForMultiListeners(KafkaListenerNameTest.java:82)

Error:  testMultipleListenerName(io.streamnative.pulsar.handlers.kop.KafkaListenerNameTest)  Time elapsed: 0.217 s  <<< FAILURE!
org.apache.pulsar.broker.PulsarServerException: java.io.IOException: Failed to bind Pulsar broker on /0.0.0.0:15002
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:783)
	at io.streamnative.pulsar.handlers.kop.KopProtocolHandlerTestBase.startBroker(KopProtocolHandlerTestBase.java:377)
	at io.streamnative.pulsar.handlers.kop.KopProtocolHandlerTestBase.startBroker(KopProtocolHandlerTestBase.java:368)
	at io.streamnative.pulsar.handlers.kop.KopProtocolHandlerTestBase.internalSetup(KopProtocolHandlerTestBase.java:284)
	at io.streamnative.pulsar.handlers.kop.KafkaListenerNameTest.testMultipleListenerName(KafkaListenerNameTest.java:168)
```

It looks like all these tests failed because the address is already in use.

**Comment by BewareMyPower** [comment]
@Demogorgon314 Could you help with this issue?
