### ISSUE TITLE
[BUG]openmessage  Rebalance failed. Unable to consume

### ISSUE THREAD

**Issue by zcola** [streamnative/kop#1032]
**Describe the bug**
The version of openmessage passed the test successfully in Kop 2.8.1

but pulsar 2.9.1 and pulsar-protocol-handler-kafka-2.9.1.5.nar  in a new cluster
```
57:31.156 [pool-2-thread-1] INFO - [Consumer clientId=consumer-sub-000-a30bYPk-1, groupId=sub-000-a30bYPk] JoinGroup failed: Coordinator 7.32.133.114:9092 (id: 1487022109 rack: null) is loading the group.
09:57:31.156 [pool-2-thread-1] INFO - [Consumer clientId=consumer-sub-000-a30bYPk-1, groupId=sub-000-a30bYPk] Rebalance failed.
57:34.715 [main] INFO - All consumers are ready
09:57:34.717 [main] INFO - ----- Starting warm-up traffic ------
09:57:34.814 [pool-2-thread-1] ERROR - exception occur while consuming message
java.lang.IllegalStateException: Unexpected error code 7 while fetching at offset 1 from topic-partition test-topic-Z3GBAmA-0000-9
        at org.apache.kafka.clients.consumer.internals.Fetcher.initializeCompletedFetch(Fetcher.java:1339) ~[kafka-clients-2.8.1.jar:?]
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:613) ~[kafka-clients-2.8.1.jar:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1303) ~[kafka-clients-2.8.1.jar:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1237) ~[kafka-clients-2.8.1.jar:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1210) ~[kafka-clients-2.8.1.jar:?]
        at io.openmessaging.benchmark.driver.kafka.KafkaBenchmarkConsumer.lambda$new$0(KafkaBenchmarkConsumer.java:58) ~[driver-kafka-0.0.1-SNAPSHOT.jar:?]
```
**To Reproduce**

```
bin/benchmark --drivers tests/test/drivers/20220124095728/kafka.yaml --output tests/test/results/16430182481-topics-16-partitions-1-producers-1-subscriptions-1-consumers-2000000-producer_rate-0G-backlog-400B_kafka/result.json tests/test/workloads/20220124095728/1-topics-16-partitions-1-producers-1-subscriptions-1-consumers-2000000-producer_rate-0G-backlog-400B.yaml

```

**Expected behavior**

**Screenshots**

**Additional context**
[docker_broker-2022-01-24.log](https://github.com/streamnative/kop/files/7924657/docker_broker-2022-01-24.log)

**Comment by zcola** [comment]
Additional information

4 bookie，4 brokers are scaled down to a single broker

openmessage log
[stdout.log](https://github.com/streamnative/kop/files/7930267/stdout.log)

broker log
[docker_broker-2022-01-25.log](https://github.com/streamnative/kop/files/7930281/docker_broker-2022-01-25.log)

broker conf
[broker_conf.log](https://github.com/streamnative/kop/files/7930304/broker_conf.log)

**Comment by zcola** [comment]
[core.dump.log](https://github.com/streamnative/kop/files/7930346/core.dump.log)
jstack

**Comment by Demogorgon314** [comment]
The NPE log in broker.
```shell
2022-01-25T02:51:03,300+0000 [pulsar-io-4-2] WARN  io.netty.util.concurrent.AbstractEventExecutor - A task raised an exception. Task: io.streamnative.pulsar.handlers.kop.KafkaRequestHandler$$Lambda$1431/0x0000000840849c40@63abe15f
java.lang.NullPointerException: null
#011at io.streamnative.pulsar.handlers.kop.MessageFetchContext.onDataWrittenToSomePartition(MessageFetchContext.java:234) ~[?:?]
#011at io.streamnative.pulsar.handlers.kop.DelayedFetch.tryComplete(DelayedFetch.java:63) ~[?:?]
#011at io.streamnative.pulsar.handlers.kop.utils.delayed.DelayedOperation.maybeTryComplete(DelayedOperation.java:127) ~[?:?]
#011at io.streamnative.pulsar.handlers.kop.utils.delayed.DelayedOperationPurgatory$Watchers.tryCompleteWatched(DelayedOperationPurgatory.java:352) ~[?:?]
#011at io.streamnative.pulsar.handlers.kop.utils.delayed.DelayedOperationPurgatory.checkAndComplete(DelayedOperationPurgatory.java:229) ~[?:?]
#011at io.streamnative.pulsar.handlers.kop.KafkaRequestHandler.lambda$notifyPendingFetches$32(KafkaRequestHandler.java:1008) ~[?:?]
#011at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
#011at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
#011at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [io.netty-netty-transport-classes-epoll-4.1.72.Final.jar:4.1.72.Final]
#011at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
#011at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
#011at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
#011at java.lang.Thread.run(Thread.java:829) [?:?]
```

```shell
2022-01-25T02:51:16,718+0000 [pulsar-io-4-2] WARN  io.netty.util.concurrent.AbstractEventExecutor - A task raised an exception. Task: io.streamnative.pulsar.handlers.kop.KafkaRequestHandler$$Lambda$1431/0x0000000840849c40@5551bea9
io.streamnative.pulsar.handlers.kop.utils.KopTopic$KoPTopicIllegalArgumentException: Invalid short topic name 'test-topic-vB2XwRg-0000', it should be in the format of <tenant>/<namespace>/<topic> or <topic>
#011at io.streamnative.pulsar.handlers.kop.utils.KopTopic.expandToFullName(KopTopic.java:77) ~[?:?]
#011at io.streamnative.pulsar.handlers.kop.utils.KopTopic.<init>(KopTopic.java:59) ~[?:?]
#011at io.streamnative.pulsar.handlers.kop.utils.KopTopic.toString(KopTopic.java:96) ~[?:?]
#011at io.streamnative.pulsar.handlers.kop.MessageFetchContext.lambda$handleFetch$4(MessageFetchContext.java:303) ~[?:?]
#011at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:?]
#011at io.streamnative.pulsar.handlers.kop.MessageFetchContext.handleFetch(MessageFetchContext.java:300) ~[?:?]
#011at io.streamnative.pulsar.handlers.kop.MessageFetchContext.onDataWrittenToSomePartition(MessageFetchContext.java:239) ~[?:?]
#011at io.streamnative.pulsar.handlers.kop.DelayedFetch.tryComplete(DelayedFetch.java:63) ~[?:?]
#011at io.streamnative.pulsar.handlers.kop.utils.delayed.DelayedOperation.maybeTryComplete(DelayedOperation.java:127) ~[?:?]
#011at io.streamnative.pulsar.handlers.kop.utils.delayed.DelayedOperationPurgatory$Watchers.tryCompleteWatched(DelayedOperationPurgatory.java:352) ~[?:?]
#011at io.streamnative.pulsar.handlers.kop.utils.delayed.DelayedOperationPurgatory.checkAndComplete(DelayedOperationPurgatory.java:229) ~[?:?]
#011at io.streamnative.pulsar.handlers.kop.KafkaRequestHandler.lambda$notifyPendingFetches$32(KafkaRequestHandler.java:1008) ~[?:?]
#011at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
#011at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
#011at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [io.netty-netty-transport-classes-epoll-4.1.72.Final.jar:4.1.72.Final]
#011at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
#011at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
#011at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
#011at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by Demogorgon314** [comment]
Here is a race condition, the `onDataWrittenToSomePartition` will call twice or more times.
```shell
--- a/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/DelayedFetch.java
+++ b/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/DelayedFetch.java
@@ -59,8 +59,9 @@ public class DelayedFetch extends DelayedOperation {
             // if we are here then we were waiting for the condition
             // someone wrote some messages to one of the topics
             // trigger the Fetch from scratch
-            restarted.set(true);
-            messageFetchContext.onDataWrittenToSomePartition();
+            if (restarted.compareAndSet(false, true)) {
+                messageFetchContext.onDataWrittenToSomePartition();
+            }
             return true;
         }
```
