### ISSUE TITLE
Flaky-test: IdempotentProducerTest.testIdempotentProducer

### ISSUE THREAD

**Issue by BewareMyPower** [streamnative/kop#1053]
IdempotentProducerTest is flaky. The testIdempotentProducer test method fails sporadically.

[example failure](https://github.com/streamnative/kop/runs/5107060964?check_suite_focus=true)

```
Error:  testIdempotentProducer(io.streamnative.pulsar.handlers.kop.IdempotentProducerTest)  Time elapsed: 1.34 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<test[510]> but was:<test[824]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at io.streamnative.pulsar.handlers.kop.IdempotentProducerTest.testIdempotentProducer(IdempotentProducerTest.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by BewareMyPower** [comment]
The test is still flaky, see [example failure](https://github.com/streamnative/kop/runs/5232538770?check_suite_focus=true). PTAL. @Demogorgon314 

```
Error:  testIdempotentProducer(io.streamnative.pulsar.handlers.kop.IdempotentProducerTest)  Time elapsed: 20.014 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method io.streamnative.pulsar.handlers.kop.IdempotentProducerTest.testIdempotentProducer() didn't finish within the time-out [200](https://github.com/streamnative/kop/runs/5232538770?check_suite_focus=true#step:5:200)00
	at sun.nio.ch.FileDispatcherImpl.preClose0(Native Method)
	at sun.nio.ch.SocketDispatcher.preClose(SocketDispatcher.java:59)
	at sun.nio.ch.SocketChannelImpl.implCloseSelectableChannel(SocketChannelImpl.java:837)
	at java.nio.channels.spi.AbstractSelectableChannel.implCloseChannel(AbstractSelectableChannel.java:241)
	at java.nio.channels.spi.AbstractInterruptibleChannel$1.interrupt(AbstractInterruptibleChannel.java:165)
	at java.nio.channels.spi.AbstractInterruptibleChannel.begin(AbstractInterruptibleChannel.java:173)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:496)
	at java.nio.channels.SocketChannel.write(SocketChannel.java:502)
	at org.apache.kafka.common.network.PlaintextTransportLayer.write(PlaintextTransportLayer.java:153)
	at org.apache.kafka.common.network.ByteBufferSend.writeTo(ByteBufferSend.java:60)
	at org.apache.kafka.common.network.KafkaChannel.send(KafkaChannel.java:339)
	at org.apache.kafka.common.network.KafkaChannel.write(KafkaChannel.java:310)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:512)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:425)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:510)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:271)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:218)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsSync(ConsumerCoordinator.java:682)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.maybeAutoCommitOffsetsSync(ConsumerCoordinator.java:741)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.close(ConsumerCoordinator.java:573)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2140)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2108)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:[205](https://github.com/streamnative/kop/runs/5232538770?check_suite_focus=true#step:5:205)9)
	at io.streamnative.pulsar.handlers.kop.IdempotentProducerTest.testIdempotentProducer(IdempotentProducerTest.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by BewareMyPower** [comment]
Another failure: https://github.com/streamnative/kop/runs/5316819259?check_suite_focus=true (it works well in my local env)

**Comment by BewareMyPower** [comment]
It's still very flaky, for example, https://github.com/streamnative/kop/runs/5506440506?check_suite_focus=true.

**Comment by BewareMyPower** [comment]
```
Error:  testIdempotentProducer(io.streamnative.pulsar.handlers.kop.IdempotentProducerTest)  Time elapsed: 35.011 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method io.streamnative.pulsar.handlers.kop.IdempotentProducerTest.testIdempotentProducer() didn't finish within the time-out 35000
	at org.apache.kafka.common.utils.LogContext$LocationAwareKafkaLogger.debug(LogContext.java:215)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.maybeAutoCommitOffsetsSync(ConsumerCoordinator.java:740)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.close(ConsumerCoordinator.java:573)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2140)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2108)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2059)
	at io.streamnative.pulsar.handlers.kop.IdempotentProducerTest.testIdempotentProducer(IdempotentProducerTest.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:[266](https://github.com/streamnative/kop/runs/5506440506?check_suite_focus=true#step:5:266))
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by BewareMyPower** [comment]
https://github.com/streamnative/kop/runs/5460013350?check_suite_focus=true

```
Error:  testIdempotentProducer(io.streamnative.pulsar.handlers.kop.IdempotentProducerTest)  Time elapsed: 35.016 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method io.streamnative.pulsar.handlers.kop.IdempotentProducerTest.testIdempotentProducer() didn't finish within the time-out 35000
	at org.apache.kafka.common.errors.InterruptException.<init>(InterruptException.java:30)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.maybeThrowInterruptException(ConsumerNetworkClient.java:504)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:287)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1247)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1187)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1154)
	at io.streamnative.pulsar.handlers.kop.IdempotentProducerTest.testIdempotentProducer(IdempotentProducerTest.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```
