### ISSUE TITLE
Flaky-test: DistributedClusterTest.testMultiBrokerProduceAndConsumeOnePartitionedTopic

### ISSUE THREAD

**Issue by BewareMyPower** [streamnative/kop#1056]
DistributedClusterTest is flaky. The testMultiBrokerProduceAndConsumeOnePartitionedTopic test method fails sporadically.

[example failure](https://github.com/streamnative/kop/runs/5110560996?check_suite_focus=true)

```
Error:  testMultiBrokerProduceAndConsumeOnePartitionedTopic(io.streamnative.pulsar.handlers.kop.DistributedClusterTest)  Time elapsed: 30.013 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method io.streamnative.pulsar.handlers.kop.DistributedClusterTest.testMultiBrokerProduceAndConsumeOnePartitionedTopic() didn't finish within the time-out 30000
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:61)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

Error:  cleanup(io.streamnative.pulsar.handlers.kop.DistributedClusterTest)  Time elapsed: 60.017 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method io.streamnative.pulsar.handlers.kop.DistributedClusterTest.cleanup() didn't finish within the time-out 30000
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:837)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:999)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1308)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at org.eclipse.jetty.io.ManagedSelector.doStop(ManagedSelector.java:140)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:94)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:180)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:201)
	at org.eclipse.jetty.io.SelectorManager.doStop(SelectorManager.java:281)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:94)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:180)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:201)
	at org.eclipse.jetty.server.AbstractConnector.doStop(AbstractConnector.java:374)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStop(AbstractNetworkConnector.java:88)
	at org.eclipse.jetty.server.ServerConnector.doStop(ServerConnector.java:246)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:94)
	at org.eclipse.jetty.server.Server.doStop(Server.java:459)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:94)
	at org.apache.pulsar.broker.web.WebService.close(WebService.java:262)
	at org.apache.pulsar.broker.PulsarService.closeAsync(PulsarService.java:404)
	at org.apache.pulsar.broker.PulsarService$MockitoMock$[174](https://github.com/streamnative/kop/runs/5110560996?check_suite_focus=true#step:5:174)2[181](https://github.com/streamnative/kop/runs/5110560996?check_suite_focus=true#step:5:181)135.closeAsync$accessor$8hZPF0FS(Unknown Source)
	at org.apache.pulsar.broker.PulsarService$MockitoMock$1742181135$auxiliary$LWXZLkK7.call(Unknown Source)
	at org.mockito.internal.invocation.RealMethod$FromCallable$1.call(RealMethod.java:40)
	at org.mockito.internal.invocation.RealMethod$FromBehavior.invoke(RealMethod.java:62)
	at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:127)
	at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:43)
	at org.mockito.Answers.answer(Answers.java:100)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:35)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:63)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:49)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(MockMethodInterceptor.java:110)
	at org.apache.pulsar.broker.PulsarService$MockitoMock$1742181135.closeAsync(Unknown Source)
	at org.apache.pulsar.broker.PulsarService.close(PulsarService.java:367)
	at org.apache.pulsar.broker.PulsarService$MockitoMock$1742181135.close$accessor$8hZPF0FS(Unknown Source)
	at org.apache.pulsar.broker.PulsarService$MockitoMock$1742181135$auxiliary$GVaGa6RW.call(Unknown Source)
	at org.mockito.internal.invocation.RealMethod$FromCallable$1.call(RealMethod.java:40)
	at org.mockito.internal.invocation.RealMethod$FromBehavior.invoke(RealMethod.java:62)
	at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:127)
	at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:43)
	at org.mockito.Answers.answer(Answers.java:100)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:35)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:63)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:49)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(MockMethodInterceptor.java:110)
	at org.apache.pulsar.broker.PulsarService$MockitoMock$1742181135.close(Unknown Source)
	at io.streamnative.pulsar.handlers.kop.DistributedClusterTest.stopBroker(DistributedClusterTest.java:153)
	at io.streamnative.pulsar.handlers.kop.KopProtocolHandlerTestBase.internalCleanup(KopProtocolHandlerTestBase.java:330)
	at io.streamnative.pulsar.handlers.kop.DistributedClusterTest.cleanup(DistributedClusterTest.java:[185](https://github.com/streamnative/kop/runs/5110560996?check_suite_focus=true#step:5:185))
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by Demogorgon314** [comment]
It's might be fixed by apache/pulsar#14060, we should wait for the new pulsar release.

**Comment by BewareMyPower** [comment]
@Demogorgon314 I think we can simply remove the call of `deletePartitionedTopic`. It's not necessary to delete the topics because the cleanup method of `DistributedClusterTest` is annotated with `@AfterMethod`.

**Comment by Demogorgon314** [comment]
Yes, I'll push a PR to remove it.
