### ISSUE TITLE
[BUG] Failed to get owned topic list caused by getListOfNonPersistentTopics

### ISSUE THREAD

**Issue by BewareMyPower** [streamnative/kop#1134]
**Describe the bug**

There is something wrong at Pulsar side that `NamespaceService#getListOfNonPersistentTopics` might fail. It would lead to a consistent failure in `CacheInvalidator` and `TransactionStateRecover`.

```
2022-03-04T09:07:33,952+0000 [metadata-store-6-1] ERROR io.streamnative.pulsar.handlers.kop.KafkaProtocolHandler - Failed to get owned topic list for CacheInvalidator when triggering bundle ownership change pulsar/10.0.0.26:8080/0x00000000_0xffffffff.
java.util.concurrent.CompletionException: org.apache.pulsar.broker.web.RestException: Namespace not found
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1099) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235) ~[?:?]
        at org.apache.pulsar.broker.namespace.NamespaceService.getListOfNonPersistentTopics(NamespaceService.java:1214) ~[io.streamnative-pulsar-broker-2.9.2.6.jar:2.9.2.6]
        at org.apache.pulsar.broker.namespace.NamespaceService.getFullListOfTopics(NamespaceService.java:1096) ~[io.streamnative-pulsar-broker-2.9.2.6.jar:2.9.2.6]
        at org.apache.pulsar.broker.namespace.NamespaceService.getOwnedTopicListForNamespaceBundle(NamespaceService.java:1103) ~[io.streamnative-pulsar-broker-2.9.2.6.jar:2.9.2.6]
        at io.streamnative.pulsar.handlers.kop.KafkaProtocolHandler$CacheInvalidator.invalidateBundleCache(KafkaProtocolHandler.java:155) ~[?:?]
        at io.streamnative.pulsar.handlers.kop.KafkaProtocolHandler$CacheInvalidator.onLoad(KafkaProtocolHandler.java:183) ~[?:?]
        at org.apache.pulsar.broker.namespace.NamespaceService.notifyNamespaceBundleOwnershipListener(NamespaceService.java:1077) ~[io.streamnative-pulsar-broker-2.9.2.6.jar:2.9.2.6]
        at org.apache.pulsar.broker.namespace.NamespaceService.lambda$addNamespaceBundleOwnershipListener$33(NamespaceService.java:1068) ~[io.streamnative-pulsar-broker-2.9.2.6.jar:2.9.2.6]
```

It looks like there is something wrong with the `NamespaceService#getListOfNonPersistentTopics` method, maybe we can fix it at Pulsar side in future.

However, since all Kafka topics should be persistent, there is no need to call `getListOfNonPersistentTopics`.

**To Reproduce**
It occurred in a 2 nodes test cluster.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by BewareMyPower** [comment]
If  `onLoad` or `unLoad` method of `CacheInvalidator` failed, then the namespace bundle listener would work. Maybe it was related to https://github.com/streamnative/kop/issues/1111.
