### ISSUE TITLE
[BUG] NPE when handle produce request

### ISSUE THREAD

**Issue by Demogorgon314** [streamnative/kop#1147]
**Describe the bug**
```
2022-03-09T04:25:01,041+0000 [pulsar-io-4-10] ERROR io.streamnative.pulsar.handlers.kop.storage.PartitionLog - Failed to handle produce request for public/default/perf-t1-1
java.lang.NullPointerException: null
	at io.streamnative.pulsar.handlers.kop.format.EncodeResult.updateProducerStats(EncodeResult.java:93) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.storage.PartitionLog.publishMessages(PartitionLog.java:265) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.storage.PartitionLog.lambda$appendRecords$2(PartitionLog.java:218) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.storage.PartitionLog.appendRecords(PartitionLog.java:226) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.storage.ReplicaManager.lambda$appendRecords$5(ReplicaManager.java:110) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.storage.ReplicaManager.appendRecords(ReplicaManager.java:101) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.KafkaRequestHandler.lambda$handleProduceRequest$34(KafkaRequestHandler.java:783) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.KafkaRequestHandler.lambda$null$35(KafkaRequestHandler.java:832) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883) ~[?:?]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.KafkaRequestHandler.lambda$handleProduceRequest$36(KafkaRequestHandler.java:816) ~[?:?]
	at java.util.HashMap.forEach(HashMap.java:1337) [?:?]
	at io.streamnative.pulsar.handlers.kop.KafkaRequestHandler.handleProduceRequest(KafkaRequestHandler.java:805) [MPmR-FPsCFvROPJWiIADMw/:?]
	at io.streamnative.pulsar.handlers.kop.KafkaCommandDecoder.channelRead(KafkaCommandDecoder.java:271) [MPmR-FPsCFvROPJWiIADMw/:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [io.netty-netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [io.netty-netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [io.netty-netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [io.netty-netty-codec-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [io.netty-netty-codec-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [io.netty-netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [io.netty-netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [io.netty-netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [io.netty-netty-handler-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [io.netty-netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [io.netty-netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [io.netty-netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [io.netty-netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [io.netty-netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [io.netty-netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [io.netty-netty-transport-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [io.netty-netty-transport-classes-epoll-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [io.netty-netty-transport-classes-epoll-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [io.netty-netty-transport-classes-epoll-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [io.netty-netty-common-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty-netty-common-4.1.74.Final.jar:4.1.74.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.74.Final.jar:4.1.74.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**To Reproduce**
It occurred in a 2 nodes test cluster.

**Comment by wangjialing218** [comment]
I also met this issue in performace test.
May be it's related with exception during appendRecords, we should log the error, return `Errors` in `ProduceResponse.PartitionResponse`.
https://github.com/streamnative/kop/blob/f198af620d27af342c5042b5765a41acf83dfa36/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java#L793

**Comment by BewareMyPower** [comment]
> Maybe it's related with exception during appendRecords, we should log the error, return Errors in ProduceResponse.PartitionResponse.

I think it's another issue. We need to make it clear whether the exception can be mapped to a `Errors`.
