### ISSUE TITLE
Flaky-test: BasicEndToEndKafkaTest.testDeletePartition

### ISSUE THREAD

**Issue by BewareMyPower** [streamnative/kop#1161]
BasicEndToEndKafkaTest is flaky. The testDeletePartition test method fails sporadically.

[example failure](https://github.com/streamnative/kop/runs/5492449505?check_suite_focus=true)

```
Error:  testDeletePartition(io.streamnative.pulsar.handlers.kop.BasicEndToEndKafkaTest)  Time elapsed: 20.014 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method io.streamnative.pulsar.handlers.kop.BasicEndToEndKafkaTest.testDeletePartition() didn't finish within the time-out 20000
	at io.streamnative.pulsar.handlers.kop.BasicEndToEndKafkaTest.testDeletePartition(BasicEndToEndKafkaTest.java:417)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by BewareMyPower** [comment]
<img width="755" alt="image" src="https://user-images.githubusercontent.com/18204803/157798441-1a01e0bf-607a-4723-aa6b-6a87ad3f0fc3.png">

It's very flaky and can be reproduced easily.
