### ISSUE TITLE
[BUG] testListOffsetForEmptyRolloverLedger failed for 2.10.0.0-rc-12

### ISSUE THREAD

**Issue by BewareMyPower** [streamnative/kop#1175]
**Describe the bug**
See https://github.com/streamnative/kop/runs/5521089422?check_suite_focus=true

```
Error:  testListOffsetForEmptyRolloverLedger(io.streamnative.pulsar.handlers.kop.MultiLedgerTest)  Time elapsed: 4.026 s  <<< FAILURE!
org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in io.streamnative.pulsar.handlers.kop.MultiLedgerTest that uses org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl was not fulfilled within 3 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:864)
	at io.streamnative.pulsar.handlers.kop.MultiLedgerTest.testListOffsetForEmptyRolloverLedger(MultiLedgerTest.java:213)
```

It looks like `ManagedLedgerImpl#ledgers` was not cleared after `rollCurrentLedgerIfFull` was called.

The test could pass for Pulsar 2.10.0.0-rc-11.

**To Reproduce**

Run `MultiLedgerTest.testListOffsetForEmptyRolloverLedger`.

**Expected behavior**
The test should pass.

**Comment by BewareMyPower** [comment]
After I reverted both https://github.com/apache/pulsar/pull/14664 and https://github.com/apache/pulsar/pull/14545, the test passed. We need to confirm the reason.
