### ISSUE TITLE
Flaky-test: SaslOauthKopHandlersTest.testGrantAndRevokePermission

### ISSUE THREAD

**Issue by BewareMyPower** [streamnative/kop#1295]
SaslOauthKopHandlersTest is flaky. The testGrantAndRevokePermission test method fails sporadically.

[example failure](https://github.com/streamnative/kop/runs/6549389734?check_suite_focus=true)

```
Error:  Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 21.066 s <<< FAILURE! - in io.streamnative.pulsar.handlers.kop.SaslOauthKopHandlersTest
Error:  testGrantAndRevokePermission(io.streamnative.pulsar.handlers.kop.SaslOauthKopHandlersTest)  Time elapsed: 1.57 s  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at io.streamnative.pulsar.handlers.kop.SaslOauthKopHandlersTest.testGrantAndRevokePermission(SaslOauthKopHandlersTest.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by BewareMyPower** [comment]
I added a debug log like

```diff
diff --git a/pom.xml b/pom.xml
index d06d28d6..b2593248 100644
--- a/pom.xml
+++ b/pom.xml
@@ -44,7 +44,7 @@
     <lombok.version>1.18.4</lombok.version>
     <mockito.version>2.22.0</mockito.version>
     <pulsar.group.id>io.streamnative</pulsar.group.id>
-    <pulsar.version>2.8.2.14</pulsar.version>
+    <pulsar.version>2.8.3.3</pulsar.version>
     <slf4j.version>1.7.25</slf4j.version>
     <spotbugs-annotations.version>3.1.8</spotbugs-annotations.version>
     <testng.version>6.14.3</testng.version>
diff --git a/tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOauthKopHandlersTest.java b/tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOauthKopHandlersTest.java
index 229db4d2..09c1185c 100644
--- a/tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOauthKopHandlersTest.java
+++ b/tests/src/test/java/io/streamnative/pulsar/handlers/kop/SaslOauthKopHandlersTest.java
@@ -28,9 +28,11 @@ import java.util.Collections;
 import java.util.Properties;
 import java.util.concurrent.CompletableFuture;
 import java.util.concurrent.ExecutionException;
+import java.util.concurrent.atomic.AtomicInteger;
 import javax.naming.AuthenticationException;
 import javax.security.auth.login.LoginException;
 import lombok.Cleanup;
+import lombok.extern.slf4j.Slf4j;
 import org.apache.kafka.clients.consumer.ConsumerRecords;
 import org.apache.kafka.clients.consumer.KafkaConsumer;
 import org.apache.kafka.clients.producer.KafkaProducer;
@@ -62,6 +64,7 @@ import org.testng.annotations.Test;
  * @see OauthLoginCallbackHandler
  * @see OauthValidatorCallbackHandler
  */
+@Slf4j
 public class SaslOauthKopHandlersTest extends SaslOauthBearerTestBase {
 
     private static final String ADMIN_USER = "simple_client_id";
@@ -119,10 +122,12 @@ public class SaslOauthKopHandlersTest extends SaslOauthBearerTestBase {
         super.testSimpleProduceConsume();
     }
 
-    @Test(timeOut = 15000)
+    private static final AtomicInteger ID = new AtomicInteger(0);
+
+    @Test(timeOut = 15000, invocationCount = 10)
     public void testGrantAndRevokePermission() throws Exception {
         final String namespace = conf.getKafkaTenant() + "/" + conf.getKafkaNamespace();
-        final String topic = "test-grant-and-revoke-permission";
+        final String topic = "test-grant-and-revoke-permission-" + ID.getAndIncrement();
         final String role = "normal-role-" + System.currentTimeMillis();
         final String clientCredentialPath = HydraOAuthUtils.createOAuthClient(role, "secret");
 
@@ -145,6 +150,7 @@ public class SaslOauthKopHandlersTest extends SaslOauthBearerTestBase {
             producer.send(new ProducerRecord<>(topic, "msg-1")).get();
             Assert.fail(role + " should not have permission to produce");
         } catch (ExecutionException e) {
+            log.info("Failed to send: ", e);
             Assert.assertTrue(e.getCause() instanceof TopicAuthorizationException);
         }
 
```

and found it could failed with `NetworkException`.

```
15:14:14.558 [TestNG-method=testGrantAndRevokePermission-1:io.streamnative.pulsar.handlers.kop.SaslOauthKopHandlersTest@153] INFO  io.streamnative.pulsar.handlers.kop.SaslOauthKopHandlersTest - Failed to send: 
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.NetworkException: The server disconnected before a response was received.
	at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.valueOrError(FutureRecordMetadata.java:94) ~[kafka-clients-2.0.0.jar:?]
	at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.get(FutureRecordMetadata.java:64) ~[kafka-clients-2.0.0.jar:?]
	at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.get(FutureRecordMetadata.java:29) ~[kafka-clients-2.0.0.jar:?]
	at io.streamnative.pulsar.handlers.kop.SaslOauthKopHandlersTest.testGrantAndRevokePermission(SaslOauthKopHandlersTest.java:150) 
```

There is a NPE.

```
15:14:14.556 [ForkJoinPool.commonPool-worker-2:org.apache.pulsar.broker.service.Producer@644] WARN  org.apache.pulsar.broker.service.Producer - [null] Get unexpected error while autorizing [persistent://public/default/test-grant-and-revoke-permission-1-partition-0]  null
java.lang.NullPointerException: null
	at io.streamnative.pulsar.handlers.kop.SaslOauthKopHandlersTest$OauthMockAuthorizationProvider.isSuperUser(SaslOauthKopHandlersTest.java:240) ~[test-classes/:?]
	at org.apache.pulsar.broker.authorization.AuthorizationService.canProduceAsync(AuthorizationService.java:187) ~[pulsar-broker-common-2.8.3.3.jar:2.8.3.3]
	at org.apache.pulsar.broker.authorization.AuthorizationService.canProduce(AuthorizationService.java:228) ~[pulsar-broker-common-2.8.3.3.jar:2.8.3.3]
	at org.apache.pulsar.broker.service.Producer.checkPermissions(Producer.java:639) ~[pulsar-broker-2.8.3.3.jar:2.8.3.3]
```

**Comment by BewareMyPower** [comment]
It looks like a bug for KoP 2.8.x and 2.9.x. I switched to branch-2.10.0 and it never failed.
