### ISSUE TITLE
FlinkKafkaProducer Semantic.EXACTLY_ONCE issue

### ISSUE THREAD

**Issue by Koh-Meta** [streamnative/kop#1333]
**Describe the bug**
FlinkKafkaProducer encounter issue with FlinkKafkaProducer.Semantic.EXACTLY_ONCE.

**To Reproduce**
1. In apache-pulsar/conf/broker.conf, set transactionCoordinatorEnabled=true
2. Restart the broker
3. Added FlinkKafkaProducer.Semantic.EXACTLY_ONCE.
![image](https://user-images.githubusercontent.com/107404257/173340340-c51f9107-f06b-4c59-8a11-9ba20252b49c.png)
4. Encountered error: Timeout expired after 60000milliseconds while awaiting InitProducerId
![image](https://user-images.githubusercontent.com/107404257/173341042-39ea0b23-a03a-4444-861a-338bb463b1fb.png)
5. No such issue with FlinkKafkaProducer.Semantic.AT_LEAST_ONCE

**Desktop**
ubuntu 20, pulsar 2.10.0, kop 2.10, flink 1.12

**Comment by BewareMyPower** [comment]
What's your KoP version? This config has been renamed with `kafkaTransactionCoordinatorEnabled` in #939.

**Comment by Koh-Meta** [comment]
Hi, good day.
My KoP version is 2.10.0.3.
In broker.conf, kafkaTransactionCoordinatorEnabled = true and brokerDeduplicationEnabled = true.

**Comment by BewareMyPower** [comment]
It looks like the `InitProducerId` request was stuck. To verify whether it's related to Flink implementation, could you run the following example Java application?

```java
        final Properties props = newKafkaProducerProperties();
        props.setProperty(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092"/* Replace with your own Kafka URL */);
        props.setProperty(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName());
        props.setProperty(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName());
        props.put(ProducerConfig.TRANSACTION_TIMEOUT_CONFIG, "1");
        props.put(ProducerConfig.ENABLE_IDEMPOTENCE_CONFIG, "true");
        props.put(ProducerConfig.TRANSACTIONAL_ID_CONFIG, "prod-1");

        final KafkaProducer<String, String> producer = new KafkaProducer<>(props);
        producer.initTransactions(); // it sends the InitProducerId request
        producer.close();
```

**Comment by Koh-Meta** [comment]
Hi, thanks for the reply. Sadly, I haven't have the chance to try out the example you have given. I will be sure to give it a try when I have the time.

But I did managed to get EXACTLY_ONCE to work using a Kafka standalone server(kafka_2.13-2.7.0).
All my codes are the same as when I am using KoP.

**Comment by Koh-Meta** [comment]
Hi, good day.

Sorry for my slow reply.

I tried running the codes provided, and this is the error I encountered:
![image](https://user-images.githubusercontent.com/107404257/176591099-9440d7fc-316d-4df7-a41e-312e7f1313b1.png)


I am not sure if this is related, but I also saw such error in my broker log:
![image](https://user-images.githubusercontent.com/107404257/176591819-6486715f-f85f-4afe-86c4-b5e0eda28586.png)

**Comment by BewareMyPower** [comment]
The `LinuxbrokerHostUsageImpl` is a known bug that has already been fixed in latest release, see https://github.com/apache/pulsar/pull/14648 for more details, you can configure `loadBalancerOverrideBrokerNicSpeedGbps` with an arbitrary value as a workaround.

Could you filter the logs that include "io.streamnative.pulsar.handlers.kop.coordinator.transaction"?

----

BTW, I found there is something wrong with the transaction support. I'll open an new issue for it.

**Comment by Koh-Meta** [comment]
I have checked, and there is no "io.streamnative.pulsar.handlers.kop.coordinator.transaction" in my logs during the time that I ran the codes.

**Comment by Koh-Meta** [comment]
Hi, good day.

I have implemented KoP v2.10.1.4, and I no longer encounter the previous issue. Thanks again for the fix.


But later on, I had encountered a different error. Here is the error logs:
```
2022-07-28 01:12:18,466 INFO  org.apache.flink.streaming.api.functions.sink.TwoPhaseCommitSinkFunction [] - FlinkKafkaProducer 1/1 - restoring state
2022-07-28 01:12:18,466 WARN  org.apache.flink.streaming.api.functions.sink.TwoPhaseCommitSinkFunction [] - Transaction KafkaTransactionState [transactionalId=Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1, producerId=25004, epoch=586] has been open for 42551680 ms. This is close to or even exceeding the transaction timeout of 10000 ms.
2022-07-28 01:12:18,476 INFO  org.apache.kafka.clients.producer.ProducerConfig             [] - ProducerConfig values: 
	acks = 1
	batch.size = 16384
	bootstrap.servers = [192.168.3.2:9092]
	buffer.memory = 33554432
	client.dns.lookup = default
	client.id = 
	compression.type = none
	connections.max.idle.ms = 540000
	delivery.timeout.ms = 120000
	enable.idempotence = false
	interceptor.classes = []
	key.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
	linger.ms = 0
	max.block.ms = 60000
	max.in.flight.requests.per.connection = 5
	max.request.size = 1048576
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	receive.buffer.bytes = 32768
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 2147483647
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	security.providers = null
	send.buffer.bytes = 131072
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = https
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	transaction.timeout.ms = 10000
	transactional.id = Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1
	value.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer

2022-07-28 01:12:18,483 INFO  org.apache.kafka.clients.producer.KafkaProducer              [] - [Producer clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1, transactionalId=Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1] Instantiated a transactional producer.
2022-07-28 01:12:18,496 INFO  org.apache.kafka.clients.producer.KafkaProducer              [] - [Producer clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1, transactionalId=Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1] Overriding the default retries config to the recommended value of 2147483647 since the idempotent producer is enabled.
2022-07-28 01:12:18,496 INFO  org.apache.kafka.clients.producer.KafkaProducer              [] - [Producer clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1, transactionalId=Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1] Overriding the default acks to all since idempotence is enabled.
2022-07-28 01:12:18,501 INFO  org.apache.kafka.common.utils.AppInfoParser                  [] - Kafka version: 2.4.1
2022-07-28 01:12:18,501 INFO  org.apache.kafka.common.utils.AppInfoParser                  [] - Kafka commitId: c57222ae8cd7866b
2022-07-28 01:12:18,501 INFO  org.apache.kafka.common.utils.AppInfoParser                  [] - Kafka startTimeMs: 1658970738498
2022-07-28 01:12:18,501 INFO  org.apache.flink.streaming.connectors.kafka.FlinkKafkaProducer [] - Starting FlinkKafkaInternalProducer (1/1) to produce into default topic koh-test-flink-checkpoint4
2022-07-28 01:12:18,501 INFO  org.apache.flink.streaming.connectors.kafka.internals.FlinkKafkaInternalProducer [] - Attempting to resume transaction Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1 with producerId 25004 and epoch 586
2022-07-28 01:12:18,622 INFO  org.apache.kafka.clients.Metadata                            [] - [Producer clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1, transactionalId=Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1] Cluster ID: pulsar-cluster-1
2022-07-28 01:12:18,724 INFO  org.apache.kafka.clients.producer.KafkaProducer              [] - [Producer clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1, transactionalId=Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1] Closing the Kafka producer with timeoutMillis = 0 ms.
2022-07-28 01:12:18,724 INFO  org.apache.kafka.clients.producer.KafkaProducer              [] - [Producer clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1, transactionalId=Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1] Proceeding to force close the producer since pending requests could not be completed within timeout 0 ms.
2022-07-28 01:12:18,726 WARN  org.apache.flink.runtime.taskmanager.Task                    [] - Source: Custom Source -> Sink: Unnamed (1/1)#0 (e8f5badd7e0af0695ec5dbc797b23bce) switched from RUNNING to FAILED.
org.apache.kafka.common.KafkaException: Unhandled error in EndTxnResponse: The server experienced an unexpected error when processing the request.
	at org.apache.kafka.clients.producer.internals.TransactionManager$EndTxnHandler.handleResponse(TransactionManager.java:1362) ~[blob_p-dab1138064dbb2d3fcea71b826b490e4ebccff52-b1bb949c26be6b41d11561b6467bff3c:?]
	at org.apache.kafka.clients.producer.internals.TransactionManager$TxnRequestHandler.onComplete(TransactionManager.java:1074) ~[blob_p-dab1138064dbb2d3fcea71b826b490e4ebccff52-b1bb949c26be6b41d11561b6467bff3c:?]
	at org.apache.kafka.clients.ClientResponse.onComplete(ClientResponse.java:109) ~[blob_p-dab1138064dbb2d3fcea71b826b490e4ebccff52-b1bb949c26be6b41d11561b6467bff3c:?]
	at org.apache.kafka.clients.NetworkClient.completeResponses(NetworkClient.java:569) ~[blob_p-dab1138064dbb2d3fcea71b826b490e4ebccff52-b1bb949c26be6b41d11561b6467bff3c:?]
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:561) ~[blob_p-dab1138064dbb2d3fcea71b826b490e4ebccff52-b1bb949c26be6b41d11561b6467bff3c:?]
	at org.apache.kafka.clients.producer.internals.Sender.maybeSendAndPollTransactionalRequest(Sender.java:425) ~[blob_p-dab1138064dbb2d3fcea71b826b490e4ebccff52-b1bb949c26be6b41d11561b6467bff3c:?]
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:311) ~[blob_p-dab1138064dbb2d3fcea71b826b490e4ebccff52-b1bb949c26be6b41d11561b6467bff3c:?]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:244) ~[blob_p-dab1138064dbb2d3fcea71b826b490e4ebccff52-b1bb949c26be6b41d11561b6467bff3c:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
2022-07-28 01:12:18,726 INFO  org.apache.flink.runtime.taskmanager.Task                    [] - Freeing task resources for Source: Custom Source -> Sink: Unnamed (1/1)#0 (e8f5badd7e0af0695ec5dbc797b23bce).
2022-07-28 01:12:18,726 INFO  org.apache.flink.runtime.taskexecutor.TaskExecutor           [] - Un-registering task and sending final execution state FAILED to JobManager for task Source: Custom Source -> Sink: Unnamed (1/1)#0 e8f5badd7e0af0695ec5dbc797b23bce.
```
I am not sure if this is relevant, in my broker log, the only error that appeared around that time period is this:
```
2022-07-28T01:12:14,553+0000 [pulsar-load-manager-1-1] ERROR org.apache.pulsar.broker.loadbalance.impl.LinuxBrokerHostUsageImpl - Failed to read speed for nic wlp5s0
java.io.IOException: Invalid argument
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_312]
	at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46) ~[?:1.8.0_312]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_312]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[?:1.8.0_312]
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:159) ~[?:1.8.0_312]
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65) ~[?:1.8.0_312]
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109) ~[?:1.8.0_312]
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103) ~[?:1.8.0_312]
	at java.nio.file.Files.read(Files.java:3105) ~[?:1.8.0_312]
	at java.nio.file.Files.readAllBytes(Files.java:3158) ~[?:1.8.0_312]
	at org.apache.pulsar.broker.loadbalance.impl.LinuxBrokerHostUsageImpl.lambda$null$3(LinuxBrokerHostUsageImpl.java:260) ~[org.apache.pulsar-pulsar-broker-2.10.0.jar:2.10.0]
	at java.util.stream.ReferencePipeline$6$1.accept(ReferencePipeline.java:244) ~[?:1.8.0_312]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_312]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_312]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_312]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_312]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_312]
	at java.util.stream.DoublePipeline.collect(DoublePipeline.java:500) ~[?:1.8.0_312]
	at java.util.stream.DoublePipeline.sum(DoublePipeline.java:411) ~[?:1.8.0_312]
	at org.apache.pulsar.broker.loadbalance.impl.LinuxBrokerHostUsageImpl.lambda$getTotalNicLimitKbps$4(LinuxBrokerHostUsageImpl.java:265) ~[org.apache.pulsar-pulsar-broker-2.10.0.jar:2.10.0]
	at java.util.Optional.orElseGet(Optional.java:267) ~[?:1.8.0_312]
	at org.apache.pulsar.broker.loadbalance.impl.LinuxBrokerHostUsageImpl.getTotalNicLimitKbps(LinuxBrokerHostUsageImpl.java:257) ~[org.apache.pulsar-pulsar-broker-2.10.0.jar:2.10.0]
	at org.apache.pulsar.broker.loadbalance.impl.LinuxBrokerHostUsageImpl.calculateBrokerHostUsage(LinuxBrokerHostUsageImpl.java:104) ~[org.apache.pulsar-pulsar-broker-2.10.0.jar:2.10.0]
	at org.apache.pulsar.common.util.Runnables$CatchingAndLoggingRunnable.run(Runnables.java:54) [org.apache.pulsar-pulsar-common-2.10.0.jar:2.10.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_312]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_312]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.74.Final.jar:4.1.74.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
```

**Comment by BewareMyPower** [comment]
The "Failed to read speed for nic" bug should have been fixed by https://github.com/apache/pulsar/pull/14340 and included in Pulsar 2.10.1. You have to configure `loadBalancerOverrideBrokerNicSpeedGbps` to avoid these confused error logs.

Regarding the error for `EndTxnResponse`, could you open another issue for it and upload your broker's logs?

**Comment by Koh-Meta** [comment]
Thanks for the reply.
Understood, I will open a new issue for it.

**Comment by Koh-Meta** [comment]
Hi, I have opened a new issue as instructed. #1424

P.S. My apologies for deleting my previous message in this issue. I felt dumb for raising a new issue in an already closed issue.
And then I only saw your reply after I had remove the message. :sweat:
