### ISSUE TITLE
[BUG] Inconsistent create topic semantics with Kafka

### ISSUE THREAD

**Issue by BewareMyPower** [streamnative/kop#1380]
**Describe the bug**
In Kafka, recreating topics cannot be simply done by the combination of `deleteTopics` and `createTopics` APIs. But in KoP, we can do that.

**To Reproduce**
Given the following Kafka application:

```java
        final var topic = "my-topic";
        final var props = new Properties();
        props.put(AdminClientConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
        @Cleanup final var admin = AdminClient.create(props);
        try {
            admin.deleteTopics(Collections.singleton(topic)).all().get();
        } catch (InterruptedException | ExecutionException e) {
            System.out.println("Failed to delete " + topic + ": " + e.getMessage());
        }
        admin.createTopics(Collections.singleton(new NewTopic(topic, 2, (short) 1))).all().get();
        final var result = admin.describeTopics(Collections.singleton(topic))
                .allTopicNames().get();
        System.out.println("numPartitions: " + Optional.ofNullable(result.get(topic))
                .map(TopicDescription::partitions).orElse(Collections.emptyList()).size());
```

First, run a KoP standalone (2.10.0.7) with essential configs. Run the application previous twice, the outputs are:

```
Failed to delete my-topic: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
numPartitions: 2
```

```
RecreateTopicDemo
```

Then run a Kafka server (3.2.0) with `listeners=PLAINTEXT://:9092` config. Run the previous application twice, the outputs are:

```
Failed to delete my-topic: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
numPartitions: 2
```

```
Exception in thread "main" java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TopicExistsException: Topic 'my-topic' is marked for deletion.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:165)
	at transaction.RecreateTopicDemo.main(RecreateTopicDemo.java:25)
Caused by: org.apache.kafka.common.errors.TopicExistsException: Topic 'my-topic' is marked for deletion.
```

As we can see, the 2nd time, `createTopics` threw an exception.

**Expected behavior**
I'm not sure whether it's expected in Kafka. We need to figure out whether should we follow the same semantics with Kafka.

**Comment by BewareMyPower** [comment]
It looks like Kafka server doesn't delete the topic immediately even if the future of `deleteTopics` completed. Instead, it marked the topic as "for deletion" at the time to send the response. After sleeping for a while before `createTopics`, it worked again for Kafka server.
