### ISSUE TITLE
[BUG]Topic reader cannot be created on a partitioned topic

### ISSUE THREAD

**Issue by yuanweikang2020** [streamnative/kop#142]
**Describe the bug**
当我配置了KoP，使用Java Kafka consumer进行消费时，Pulsar出现了错误：`Topic reader cannot be created on a partitioned topic`，我的Java Kafka Consumer程序没有消费到数据，并且出现了错误：`Correlation id for response (236) does not match request (235), request header: RequestHeader(apiKey=OFFSET_COMMIT, apiVersion=4, clientId=consumer-1, correlationId=235)
`
**To Reproduce**
1. 我配置了`etc/pulsar/standalone.conf`，并且正常启动，具体配置如下：
```
### For kop config
messagingProtocols=kafka
protocolHandlerDirectory=share/java/pulsar/potocols

saslAllowedMechanisms=PLAIN

# Configuration to enable authentication and authorization
# Enable authentication
authenticationEnabled=true
# Enforce authorization
authorizationEnabled=true
```
2. 我的Java Kafka Producer程序，如下：
```java
public class ProducerDemo {
    public static void main(String[] args) {
        String tenant = "test_app/data";
        String password = "token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0X3VzZXIifQ.qWTV0-8T8DrNzxKIHhRc9BoWxiVUxCdiB2TtKsMC9yo";
        String topic = "app_binlog";

        String jaasTemplate = "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"%s\" password=\"%s\";";
        String jaasCfg = String.format(jaasTemplate, tenant, password);

        Properties producerProps = new Properties();

        producerProps.put("sasl.jaas.config", jaasCfg);

        producerProps.put("security.protocol", "SASL_PLAINTEXT");
        producerProps.put("sasl.mechanism", "PLAIN");

        producerProps.put("bootstrap.servers", "127.0.0.1:9092");
        producerProps.put("acks", "all");
        producerProps.put("retries", 0);
        producerProps.put("batch.size", 16384);
        producerProps.put("linger.ms", 1);
        producerProps.put("buffer.memory", 33554432);
        producerProps.put("key.serializer", "org.apache.kafka.common.serialization.StringSerializer");
        producerProps.put("value.serializer", "org.apache.kafka.common.serialization.StringSerializer");

        Producer<String, String> producer = new KafkaProducer<String, String>(producerProps);

        try {
            for(int i=0; i<100; i++) {
                ProducerRecord<String, String> record = new ProducerRecord<String, String>(topic, Integer.toString(i), Integer.toString(i));
                producer.send(record);
                System.out.printf("produce %s success, idx:%d\n", record.topic(), i);
                Thread.sleep(500);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}
```
这个程序可以正常生产数据，没有报错，并且在Pulsar-Manager上有显示生数据的数量
![image](https://user-images.githubusercontent.com/63803593/79683602-e3953f80-825d-11ea-98e6-edf51bf67c43.png)
3. 我的Java Kafka Consumer程序，如下：
```java
public class ConsumerDemo {

    public static void main(String[] args) {
        String tenant = "test_app/data";
        String password = "token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0X3VzZXIifQ.qWTV0-8T8DrNzxKIHhRc9BoWxiVUxCdiB2TtKsMC9yo";
        String topic = "app_binlog";

        String jaasTemplate = "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"%s\" password=\"%s\";";
        String jaasCfg = String.format(jaasTemplate, tenant, password);

        Properties consumerProps = new Properties();
        consumerProps.put("sasl.jaas.config", jaasCfg);
        consumerProps.put("security.protocol", "SASL_PLAINTEXT");
        consumerProps.put("sasl.mechanism", "PLAIN");

        consumerProps.put("bootstrap.servers", "127.0.0.1:9092");

        consumerProps.put("group.id", "test-100");
        consumerProps.put("enable.auto.commit", "true");
        consumerProps.put("auto.commit.interval.ms", "50");
        consumerProps.put("max.poll.records", 1000);
        consumerProps.put("auto.offset.reset", "earliest");
        consumerProps.put("session.timeout.ms", "30000");
        consumerProps.put("key.deserializer", "org.apache.kafka.common.serialization.StringDeserializer");
        consumerProps.put("value.deserializer", "org.apache.kafka.common.serialization.StringDeserializer");


        try {
            Consumer<String, String> consumer = new KafkaConsumer<String, String>(consumerProps);
            consumer.subscribe(Arrays.asList(topic));
            while(true) {
                ConsumerRecords<String, String> records = consumer.poll(10);
                for(ConsumerRecord<String, String> record : records) {
                    System.out.printf("offset = %d, key = %s, value = %s\n", record.offset(), record.key(), record.value());
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}
```
消费程序并未正常消费消息，并且出现错误：`Correlation id for response (236) does not match request (235), request header: RequestHeader(apiKey=OFFSET_COMMIT, apiVersion=4, clientId=consumer-1, correlationId=235)
`，Pulsar日志也出现错误：`Topic reader cannot be created on a partitioned topic`；并且还有一个很奇怪的现在，在Pulsar-Manager上显示在`Public`租户的`Default` Namespace下出现了一个`app_binlog-partition-0`的topic
![image](https://user-images.githubusercontent.com/63803593/79683543-75e91380-825d-11ea-865c-2ab00e3def6b.png)

**Expected behavior**
想请问一下，出错的原因。

**Screenshots**
Pulsar出错信息
```
16:52:45.403 [ForkJoinPool.commonPool-worker-0] WARN  io.streamnative.pulsar.handlers.kop.coordinator.group.OffsetAcker - Error when get consumer for offset ack:
java.util.concurrent.CompletionException: org.apache.pulsar.client.api.PulsarClientException: Topic reader cannot be created on a partitioned topic
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:911) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:899) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_161]
	at org.apache.pulsar.client.impl.PulsarClientImpl.lambda$doCreateReaderAsync$14(PulsarClientImpl.java:483) ~[org.apache.pulsar-pulsar-client-original-2.5.0-ad0224407.jar:2.5.0-ad0224407]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[?:1.8.0_161]
	at org.apache.pulsar.client.impl.BinaryProtoLookupService.lambda$null$6(BinaryProtoLookupService.java:167) ~[org.apache.pulsar-pulsar-client-original-2.5.0-ad0224407.jar:2.5.0-ad0224407]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_161]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[?:1.8.0_161]
	at org.apache.pulsar.client.impl.ClientCnx.handlePartitionResponse(ClientCnx.java:516) ~[org.apache.pulsar-pulsar-client-original-2.5.0-ad0224407.jar:2.5.0-ad0224407]
	at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:120) ~[org.apache.pulsar-pulsar-common-2.5.0-ad0224407.jar:2.5.0-ad0224407]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321) ~[io.netty-netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295) ~[io.netty-netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[io.netty-netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[io.netty-netty-transport-native-epoll-4.1.45.Final-linux-x86_64.jar:4.1.45.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[io.netty-netty-transport-native-epoll-4.1.45.Final-linux-x86_64.jar:4.1.45.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[io.netty-netty-transport-native-epoll-4.1.45.Final-linux-x86_64.jar:4.1.45.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[io.netty-netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty-netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty-netty-common-4.1.45.Final.jar:4.1.45.Final]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_161]
Caused by: org.apache.pulsar.client.api.PulsarClientException: Topic reader cannot be created on a partitioned topic
	... 35 more
```

**Additional context**

**Comment by sijie** [comment]
@jiazhai can you take a look at this issue?

**Comment by jiazhai** [comment]
Looks like the multi tenancy not mapped well in OffsetAcker.  And caused `OFFSET_COMMIT` command not handled right. 
In KafkaRequestHandler, the tenant/namespace, which user passed in through sasl config, is stored inside KafkaRequestHandler, but tenant/namespace is not passed into GroupCoordinator,  so when do offset related operation, it will get the tenant/namespace from config file, and get wrong topic.

We need to rethink how to support the multi tenancy .

**Comment by yuanweikang2020** [comment]
Ok, thx!

**Comment by jiazhai** [comment]
@yuanweikang2020 Would you please help try whether `String tenant = "public/defaut";` works well?

**Comment by yuanweikang2020** [comment]
我尝试了一下，不会创建类似`xxx-partition-0`的topic，但是还是会出现错误：`Correlation id for response (15) does not match request (14), request header: RequestHeader(apiKey=OFFSET_COMMIT, apiVersion=4, clientId=consumer-1, correlationId=14)`

**Comment by jiazhai** [comment]
@yuanweikang2020 What is the broker side error? It seems broker still not handled `OFFSET_COMMIT` right.
