### ISSUE TITLE
FlinkKafkaProducer encounter error on restart

### ISSUE THREAD

**Issue by Koh-Meta** [streamnative/kop#1424]
**Describe the bug**
Flink job encountered error on restart.

**To Reproduce**
1. Start flink job. Here is my codes:
````
StreamExecutionEnvironment see = StreamExecutionEnvironment.getExecutionEnvironment();
see.getConfig().setAutoWatermarkInterval(1000);
see.getCheckpointConfig().enableExternalizedCheckpoints(CheckpointConfig.ExternalizedCheckpointCleanup.RETAIN_ON_CANCELLATION);
see.getConfig().setParallelism(1);
see.getConfig().setRestartStrategy(RestartStrategies.fixedDelayRestart(1, 10000));
Properties props = new Properties();
props.setProperty("topic", "input-topic-here");
PulsarDeserializationSchema<LiveRawData> pulsarDeserialization = PulsarDeserializationSchema.valueOnly(JsonDeser.of(LiveRawData.class));
FlinkPulsarSource<LiveRawData> fps = new FlinkPulsarSource<>("service-url-here", "admin-url-here", pulsarDeserialization, props);
DataStream<LiveRawData> stream = see.addSource(fps);
Properties propsKafka = new Properties();
propsKafka.setProperty(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "kop-url-here");
propsKafka.setProperty(ProducerConfig.TRANSACTION_TIMEOUT_CONFIG, "10000");

stream
        .addSink(new FlinkKafkaProducer<>(
                "output-topic-here",
                new ObjSerializationSchema("output-topic-here"),
                propsKafka,
                FlinkKafkaProducer.Semantic.EXACTLY_ONCE
        ));
see.enableCheckpointing(5000);
see.execute("koh-test-kop");
````
2. manually cancel flink job, or kill job manager, or kill task manager, or reboot server
3. wait for flink job to restart
```
2022-07-28 01:12:18,466 INFO  org.apache.flink.streaming.api.functions.sink.TwoPhaseCommitSinkFunction [] - FlinkKafkaProducer 1/1 - restoring state
2022-07-28 01:12:18,466 WARN  org.apache.flink.streaming.api.functions.sink.TwoPhaseCommitSinkFunction [] - Transaction KafkaTransactionState [transactionalId=Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1, producerId=25004, epoch=586] has been open for 42551680 ms. This is close to or even exceeding the transaction timeout of 10000 ms.
2022-07-28 01:12:18,476 INFO  org.apache.kafka.clients.producer.ProducerConfig             [] - ProducerConfig values: 
	acks = 1
	batch.size = 16384
	bootstrap.servers = [192.168.3.2:9092]
	buffer.memory = 33554432
	client.dns.lookup = default
	client.id = 
	compression.type = none
	connections.max.idle.ms = 540000
	delivery.timeout.ms = 120000
	enable.idempotence = false
	interceptor.classes = []
	key.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
	linger.ms = 0
	max.block.ms = 60000
	max.in.flight.requests.per.connection = 5
	max.request.size = 1048576
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	receive.buffer.bytes = 32768
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 2147483647
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	security.providers = null
	send.buffer.bytes = 131072
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = https
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	transaction.timeout.ms = 10000
	transactional.id = Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1
	value.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer

2022-07-28 01:12:18,483 INFO  org.apache.kafka.clients.producer.KafkaProducer              [] - [Producer clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1, transactionalId=Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1] Instantiated a transactional producer.
2022-07-28 01:12:18,496 INFO  org.apache.kafka.clients.producer.KafkaProducer              [] - [Producer clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1, transactionalId=Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1] Overriding the default retries config to the recommended value of 2147483647 since the idempotent producer is enabled.
2022-07-28 01:12:18,496 INFO  org.apache.kafka.clients.producer.KafkaProducer              [] - [Producer clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1, transactionalId=Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1] Overriding the default acks to all since idempotence is enabled.
2022-07-28 01:12:18,501 INFO  org.apache.kafka.common.utils.AppInfoParser                  [] - Kafka version: 2.4.1
2022-07-28 01:12:18,501 INFO  org.apache.kafka.common.utils.AppInfoParser                  [] - Kafka commitId: c57222ae8cd7866b
2022-07-28 01:12:18,501 INFO  org.apache.kafka.common.utils.AppInfoParser                  [] - Kafka startTimeMs: 1658970738498
2022-07-28 01:12:18,501 INFO  org.apache.flink.streaming.connectors.kafka.FlinkKafkaProducer [] - Starting FlinkKafkaInternalProducer (1/1) to produce into default topic koh-test-flink-checkpoint4
2022-07-28 01:12:18,501 INFO  org.apache.flink.streaming.connectors.kafka.internals.FlinkKafkaInternalProducer [] - Attempting to resume transaction Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1 with producerId 25004 and epoch 586
2022-07-28 01:12:18,622 INFO  org.apache.kafka.clients.Metadata                            [] - [Producer clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1, transactionalId=Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1] Cluster ID: pulsar-cluster-1
2022-07-28 01:12:18,724 INFO  org.apache.kafka.clients.producer.KafkaProducer              [] - [Producer clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1, transactionalId=Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1] Closing the Kafka producer with timeoutMillis = 0 ms.
2022-07-28 01:12:18,724 INFO  org.apache.kafka.clients.producer.KafkaProducer              [] - [Producer clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1, transactionalId=Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-1] Proceeding to force close the producer since pending requests could not be completed within timeout 0 ms.
2022-07-28 01:12:18,726 WARN  org.apache.flink.runtime.taskmanager.Task                    [] - Source: Custom Source -> Sink: Unnamed (1/1)#0 (e8f5badd7e0af0695ec5dbc797b23bce) switched from RUNNING to FAILED.
org.apache.kafka.common.KafkaException: Unhandled error in EndTxnResponse: The server experienced an unexpected error when processing the request.
	at org.apache.kafka.clients.producer.internals.TransactionManager$EndTxnHandler.handleResponse(TransactionManager.java:1362) ~[blob_p-dab1138064dbb2d3fcea71b826b490e4ebccff52-b1bb949c26be6b41d11561b6467bff3c:?]
	at org.apache.kafka.clients.producer.internals.TransactionManager$TxnRequestHandler.onComplete(TransactionManager.java:1074) ~[blob_p-dab1138064dbb2d3fcea71b826b490e4ebccff52-b1bb949c26be6b41d11561b6467bff3c:?]
	at org.apache.kafka.clients.ClientResponse.onComplete(ClientResponse.java:109) ~[blob_p-dab1138064dbb2d3fcea71b826b490e4ebccff52-b1bb949c26be6b41d11561b6467bff3c:?]
	at org.apache.kafka.clients.NetworkClient.completeResponses(NetworkClient.java:569) ~[blob_p-dab1138064dbb2d3fcea71b826b490e4ebccff52-b1bb949c26be6b41d11561b6467bff3c:?]
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:561) ~[blob_p-dab1138064dbb2d3fcea71b826b490e4ebccff52-b1bb949c26be6b41d11561b6467bff3c:?]
	at org.apache.kafka.clients.producer.internals.Sender.maybeSendAndPollTransactionalRequest(Sender.java:425) ~[blob_p-dab1138064dbb2d3fcea71b826b490e4ebccff52-b1bb949c26be6b41d11561b6467bff3c:?]
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:311) ~[blob_p-dab1138064dbb2d3fcea71b826b490e4ebccff52-b1bb949c26be6b41d11561b6467bff3c:?]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:244) ~[blob_p-dab1138064dbb2d3fcea71b826b490e4ebccff52-b1bb949c26be6b41d11561b6467bff3c:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
2022-07-28 01:12:18,726 INFO  org.apache.flink.runtime.taskmanager.Task                    [] - Freeing task resources for Source: Custom Source -> Sink: Unnamed (1/1)#0 (e8f5badd7e0af0695ec5dbc797b23bce).
2022-07-28 01:12:18,726 INFO  org.apache.flink.runtime.taskexecutor.TaskExecutor           [] - Un-registering task and sending final execution state FAILED to JobManager for task Source: Custom Source -> Sink: Unnamed (1/1)#0 e8f5badd7e0af0695ec5dbc797b23bce.
```

**Additional context**
The KoP version I am using is 2.10.1.4.
Ubuntu 20.04, Pulsar 2.10, Flink 1.12

I managed to get EXACTLY_ONCE to work using a Kafka standalone server(version 2.7.0).
All my codes are the same as when I am using KoP.

Let me know if you need more information. Many thanks!

**Comment by Raven888888** [comment]
@BewareMyPower have you seen this error before?

**Comment by BewareMyPower** [comment]
@Raven888888 No.

@Koh-Meta Sorry for the late reply. Could you upload the broker's logs? The client side logs are usually not much helpful. If you can reproduce it easily, could you change the log level to debug?

**Comment by Demogorgon314** [comment]
@Raven888888 Can you provide the broker logs?

**Comment by Koh-Meta** [comment]
Hi, sorry for the slow reply.

As instructed, we have changed the log level to debug. Here are the logs from our broker.
```
2022-08-05T08:37:26,847+0000 [pulsar-ph-kafka-64-29] INFO  io.streamnative.pulsar.handlers.kop.KafkaRequestHandler - channel active: [id: 0x6e9edb12, L:/192.168.3.2:9092 - R:/192.168.3.3:53588]
2022-08-05T08:37:26,847+0000 [pulsar-ph-kafka-64-29] DEBUG io.streamnative.pulsar.handlers.kop.KafkaCommandDecoder - [/192.168.3.3:53588] Received kafka cmd RequestHeader(apiKey=API_VERSIONS, apiVersion=3, clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4, correlationId=0), the request content is: KafkaHeaderAndRequest(header=RequestHeader(apiKey=API_VERSIONS, apiVersion=3, clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4, correlationId=0), request={}, remoteAddress=/192.168.3.3:53588)
2022-08-05T08:37:26,847+0000 [send-response-OrderedScheduler-3-0] DEBUG io.streamnative.pulsar.handlers.kop.KafkaCommandDecoder - Write kafka cmd to client. request content: KafkaHeaderAndRequest(header=RequestHeader(apiKey=API_VERSIONS, apiVersion=3, clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4, correlationId=0), request={}, remoteAddress=/192.168.3.3:53588) responseAndRequest content: {error_code=35,api_versions=[]}
2022-08-05T08:37:26,848+0000 [pulsar-ph-kafka-64-29] DEBUG io.streamnative.pulsar.handlers.kop.KafkaCommandDecoder - [/192.168.3.3:53588] Received kafka cmd RequestHeader(apiKey=API_VERSIONS, apiVersion=0, clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4, correlationId=1), the request content is: KafkaHeaderAndRequest(header=RequestHeader(apiKey=API_VERSIONS, apiVersion=0, clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4, correlationId=1), request={}, remoteAddress=/192.168.3.3:53588)
2022-08-05T08:37:26,848+0000 [send-response-OrderedScheduler-3-0] DEBUG io.streamnative.pulsar.handlers.kop.KafkaCommandDecoder - Write kafka cmd to client. request content: KafkaHeaderAndRequest(header=RequestHeader(apiKey=API_VERSIONS, apiVersion=0, clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4, correlationId=1), request={}, remoteAddress=/192.168.3.3:53588) responseAndRequest content: {error_code=0,api_versions=[{api_key=0,min_version=0,max_version=6},{api_key=1,min_version=0,max_version=8},{api_key=2,min_version=0,max_version=3},{api_key=3,min_version=0,max_version=6},{api_key=4,min_version=0,max_version=1},{api_key=5,min_version=0,max_version=0},{api_key=6,min_version=0,max_version=4},{api_key=7,min_version=0,max_version=1},{api_key=8,min_version=0,max_version=4},{api_key=9,min_version=0,max_version=4},{api_key=10,min_version=0,max_version=2},{api_key=11,min_version=0,max_version=3},{api_key=12,min_version=0,max_version=2},{api_key=13,min_version=0,max_version=2},{api_key=14,min_version=0,max_version=2},{api_key=15,min_version=0,max_version=2},{api_key=16,min_version=0,max_version=2},{api_key=17,min_version=0,max_version=1},{api_key=18,min_version=0,max_version=2},{api_key=19,min_version=0,max_version=3},{api_key=20,min_version=0,max_version=2},{api_key=21,min_version=0,max_version=1},{api_key=22,min_version=0,max_version=1},{api_key=23,min_version=0,max_version=1},{api_key=24,min_version=0,max_version=1},{api_key=25,min_version=0,max_version=1},{api_key=26,min_version=0,max_version=1},{api_key=27,min_version=0,max_version=0},{api_key=28,min_version=0,max_version=1},{api_key=29,min_version=0,max_version=1},{api_key=30,min_version=0,max_version=1},{api_key=31,min_version=0,max_version=1},{api_key=32,min_version=0,max_version=2},{api_key=33,min_version=0,max_version=1},{api_key=34,min_version=0,max_version=1},{api_key=35,min_version=0,max_version=1},{api_key=36,min_version=0,max_version=0},{api_key=37,min_version=0,max_version=1},{api_key=38,min_version=0,max_version=1},{api_key=39,min_version=0,max_version=1},{api_key=40,min_version=0,max_version=1},{api_key=41,min_version=0,max_version=1},{api_key=42,min_version=0,max_version=1}]}
2022-08-05T08:37:26,849+0000 [pulsar-ph-kafka-64-29] DEBUG io.streamnative.pulsar.handlers.kop.KafkaCommandDecoder - [/192.168.3.3:53588] Received kafka cmd RequestHeader(apiKey=METADATA, apiVersion=6, clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4, correlationId=2), the request content is: KafkaHeaderAndRequest(header=RequestHeader(apiKey=METADATA, apiVersion=6, clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4, correlationId=2), request={topics=[],allow_auto_topic_creation=true}, remoteAddress=/192.168.3.3:53588)
2022-08-05T08:37:26,849+0000 [pulsar-ph-kafka-64-29] DEBUG io.streamnative.pulsar.handlers.kop.KafkaRequestHandler - using public as tenant
2022-08-05T08:37:26,849+0000 [send-response-OrderedScheduler-3-0] DEBUG io.streamnative.pulsar.handlers.kop.KafkaCommandDecoder - Write kafka cmd to client. request content: KafkaHeaderAndRequest(header=RequestHeader(apiKey=METADATA, apiVersion=6, clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4, correlationId=2), request={topics=[],allow_auto_topic_creation=true}, remoteAddress=/192.168.3.3:53588) responseAndRequest content: {throttle_time_ms=0,brokers=[{node_id=1036404620,host=192.168.3.3,port=9092,rack=null},{node_id=221569297,host=192.168.3.1,port=9092,rack=null},{node_id=1774485868,host=192.168.3.2,port=9092,rack=null}],cluster_id=pulsar-cluster-1,controller_id=221569297,topic_metadata=[]}
2022-08-05T08:37:26,849+0000 [pulsar-ph-kafka-64-29] DEBUG io.streamnative.pulsar.handlers.kop.KafkaCommandDecoder - [/192.168.3.3:53588] Received kafka cmd RequestHeader(apiKey=FIND_COORDINATOR, apiVersion=2, clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4, correlationId=3), the request content is: KafkaHeaderAndRequest(header=RequestHeader(apiKey=FIND_COORDINATOR, apiVersion=2, clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4, correlationId=3), request={coordinator_key=Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4,coordinator_type=1}, remoteAddress=/192.168.3.3:53588)
2022-08-05T08:37:26,849+0000 [pulsar-ph-kafka-64-29] DEBUG io.streamnative.pulsar.handlers.kop.KafkaRequestHandler - using public as tenant
2022-08-05T08:37:26,849+0000 [pulsar-ph-kafka-64-29] DEBUG io.streamnative.pulsar.handlers.kop.KafkaRequestHandler - [[id: 0x6e9edb12, L:/192.168.3.2:9092 - R:/192.168.3.3:53588]] Handle Lookup for persistent://public/__kafka/__transaction_state-partition-22
2022-08-05T08:37:26,849+0000 [pulsar-ph-kafka-64-29] DEBUG io.streamnative.pulsar.handlers.kop.KopBrokerLookupManager - Handle Lookup for topic persistent://public/__kafka/__transaction_state-partition-22
2022-08-05T08:37:26,849+0000 [pulsar-ph-kafka-64-29] DEBUG io.streamnative.pulsar.handlers.kop.KopBrokerLookupManager - [persistent://public/__kafka/__transaction_state-partition-22] Found broker's internal listener address: 192.168.3.2:6650
2022-08-05T08:37:26,849+0000 [pulsar-ph-kafka-64-29] DEBUG io.streamnative.pulsar.handlers.kop.KopBrokerLookupManager - Handle getProtocolDataToAdvertise for persistent://public/__kafka/__transaction_state-partition-22, pulsarUrl: pulsar://192.168.3.1:6650, pulsarUrlTls: null, webUrl: http://192.168.3.1:8080, webUrlTls: null kafka: Optional[PLAINTEXT://192.168.3.1:9092]
2022-08-05T08:37:26,849+0000 [pulsar-ph-kafka-64-29] DEBUG io.streamnative.pulsar.handlers.kop.KopBrokerLookupManager - Handle getProtocolDataToAdvertise for persistent://public/__kafka/__transaction_state-partition-22, pulsarUrl: pulsar://192.168.3.2:6650, pulsarUrlTls: null, webUrl: http://192.168.3.2:8080, webUrlTls: null kafka: Optional[PLAINTEXT://192.168.3.2:9092]
2022-08-05T08:37:26,849+0000 [pulsar-ph-kafka-64-29] DEBUG io.streamnative.pulsar.handlers.kop.KopBrokerLookupManager - Handle getProtocolDataToAdvertise for persistent://public/__kafka/__transaction_state-partition-22, pulsarUrl: pulsar://192.168.3.3:6650, pulsarUrlTls: null, webUrl: http://192.168.3.3:8080, webUrlTls: null kafka: Optional[PLAINTEXT://192.168.3.3:9092]
2022-08-05T08:37:26,849+0000 [pulsar-ph-kafka-64-29] DEBUG io.streamnative.pulsar.handlers.kop.KopBrokerLookupManager - Found listener PLAINTEXT://192.168.3.2:9092 for topic persistent://public/__kafka/__transaction_state-partition-22
2022-08-05T08:37:26,849+0000 [pulsar-ph-kafka-64-29] DEBUG io.streamnative.pulsar.handlers.kop.KafkaRequestHandler - Return Broker Node of /192.168.3.2:9092. 192.168.3.2:9092
2022-08-05T08:37:26,849+0000 [pulsar-ph-kafka-64-29] DEBUG io.streamnative.pulsar.handlers.kop.KafkaRequestHandler - Return PartitionMetadata node: 192.168.3.2:9092 (id: 1774485868 rack: null), topicName: persistent://public/__kafka/__transaction_state-partition-22
2022-08-05T08:37:26,849+0000 [pulsar-ph-kafka-64-29] DEBUG io.streamnative.pulsar.handlers.kop.KafkaRequestHandler - [[id: 0x6e9edb12, L:/192.168.3.2:9092 - R:/192.168.3.3:53588]] Found node 192.168.3.2:9092 (id: 1774485868 rack: null) as coordinator for key Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4 partition 22.
2022-08-05T08:37:26,849+0000 [send-response-OrderedScheduler-3-0] DEBUG io.streamnative.pulsar.handlers.kop.KafkaCommandDecoder - Write kafka cmd to client. request content: KafkaHeaderAndRequest(header=RequestHeader(apiKey=FIND_COORDINATOR, apiVersion=2, clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4, correlationId=3), request={coordinator_key=Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4,coordinator_type=1}, remoteAddress=/192.168.3.3:53588) responseAndRequest content: {throttle_time_ms=0,error_code=0,error_message=null,coordinator={node_id=1774485868,host=192.168.3.2,port=9092}}
2022-08-05T08:37:26,850+0000 [pulsar-ph-kafka-64-30] INFO  io.streamnative.pulsar.handlers.kop.KafkaRequestHandler - channel active: [id: 0xd740cefb, L:/192.168.3.2:9092 - R:/192.168.3.3:53590]
2022-08-05T08:37:26,850+0000 [pulsar-ph-kafka-64-30] DEBUG io.streamnative.pulsar.handlers.kop.KafkaCommandDecoder - [/192.168.3.3:53590] Received kafka cmd RequestHeader(apiKey=API_VERSIONS, apiVersion=3, clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4, correlationId=4), the request content is: KafkaHeaderAndRequest(header=RequestHeader(apiKey=API_VERSIONS, apiVersion=3, clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4, correlationId=4), request={}, remoteAddress=/192.168.3.3:53590)
2022-08-05T08:37:26,850+0000 [send-response-OrderedScheduler-1-0] DEBUG io.streamnative.pulsar.handlers.kop.KafkaCommandDecoder - Write kafka cmd to client. request content: KafkaHeaderAndRequest(header=RequestHeader(apiKey=API_VERSIONS, apiVersion=3, clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4, correlationId=4), request={}, remoteAddress=/192.168.3.3:53590) responseAndRequest content: {error_code=35,api_versions=[]}
2022-08-05T08:37:26,851+0000 [pulsar-ph-kafka-64-30] DEBUG io.streamnative.pulsar.handlers.kop.KafkaCommandDecoder - [/192.168.3.3:53590] Received kafka cmd RequestHeader(apiKey=API_VERSIONS, apiVersion=0, clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4, correlationId=5), the request content is: KafkaHeaderAndRequest(header=RequestHeader(apiKey=API_VERSIONS, apiVersion=0, clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4, correlationId=5), request={}, remoteAddress=/192.168.3.3:53590)
2022-08-05T08:37:26,851+0000 [send-response-OrderedScheduler-1-0] DEBUG io.streamnative.pulsar.handlers.kop.KafkaCommandDecoder - Write kafka cmd to client. request content: KafkaHeaderAndRequest(header=RequestHeader(apiKey=API_VERSIONS, apiVersion=0, clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4, correlationId=5), request={}, remoteAddress=/192.168.3.3:53590) responseAndRequest content: {error_code=0,api_versions=[{api_key=0,min_version=0,max_version=6},{api_key=1,min_version=0,max_version=8},{api_key=2,min_version=0,max_version=3},{api_key=3,min_version=0,max_version=6},{api_key=4,min_version=0,max_version=1},{api_key=5,min_version=0,max_version=0},{api_key=6,min_version=0,max_version=4},{api_key=7,min_version=0,max_version=1},{api_key=8,min_version=0,max_version=4},{api_key=9,min_version=0,max_version=4},{api_key=10,min_version=0,max_version=2},{api_key=11,min_version=0,max_version=3},{api_key=12,min_version=0,max_version=2},{api_key=13,min_version=0,max_version=2},{api_key=14,min_version=0,max_version=2},{api_key=15,min_version=0,max_version=2},{api_key=16,min_version=0,max_version=2},{api_key=17,min_version=0,max_version=1},{api_key=18,min_version=0,max_version=2},{api_key=19,min_version=0,max_version=3},{api_key=20,min_version=0,max_version=2},{api_key=21,min_version=0,max_version=1},{api_key=22,min_version=0,max_version=1},{api_key=23,min_version=0,max_version=1},{api_key=24,min_version=0,max_version=1},{api_key=25,min_version=0,max_version=1},{api_key=26,min_version=0,max_version=1},{api_key=27,min_version=0,max_version=0},{api_key=28,min_version=0,max_version=1},{api_key=29,min_version=0,max_version=1},{api_key=30,min_version=0,max_version=1},{api_key=31,min_version=0,max_version=1},{api_key=32,min_version=0,max_version=2},{api_key=33,min_version=0,max_version=1},{api_key=34,min_version=0,max_version=1},{api_key=35,min_version=0,max_version=1},{api_key=36,min_version=0,max_version=0},{api_key=37,min_version=0,max_version=1},{api_key=38,min_version=0,max_version=1},{api_key=39,min_version=0,max_version=1},{api_key=40,min_version=0,max_version=1},{api_key=41,min_version=0,max_version=1},{api_key=42,min_version=0,max_version=1}]}
2022-08-05T08:37:26,952+0000 [pulsar-ph-kafka-64-30] DEBUG io.streamnative.pulsar.handlers.kop.KafkaCommandDecoder - [/192.168.3.3:53590] Received kafka cmd RequestHeader(apiKey=END_TXN, apiVersion=1, clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4, correlationId=6), the request content is: KafkaHeaderAndRequest(header=RequestHeader(apiKey=END_TXN, apiVersion=1, clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4, correlationId=6), request={transactional_id=Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4,producer_id=25012,producer_epoch=1368,transaction_result=true}, remoteAddress=/192.168.3.3:53590)
2022-08-05T08:37:26,952+0000 [pulsar-ph-kafka-64-30] DEBUG io.streamnative.pulsar.handlers.kop.KafkaRequestHandler - using public as tenant
2022-08-05T08:37:26,952+0000 [pulsar-ph-kafka-64-30] ERROR io.streamnative.pulsar.handlers.kop.coordinator.transaction.TransactionCoordinator - Aborting append of COMMIT to transaction log with coordinator and returning UNKNOWN_SERVER_ERROR error to client for Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4's EndTransaction request
2022-08-05T08:37:26,952+0000 [send-response-OrderedScheduler-1-0] DEBUG io.streamnative.pulsar.handlers.kop.KafkaCommandDecoder - Write kafka cmd to client. request content: KafkaHeaderAndRequest(header=RequestHeader(apiKey=END_TXN, apiVersion=1, clientId=producer-Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4, correlationId=6), request={transactional_id=Source: Custom Source -> Sink: Unnamed-7df19f87deec5680128845fd9a6ca18d-4,producer_id=25012,producer_epoch=1368,transaction_result=true}, remoteAddress=/192.168.3.3:53590) responseAndRequest content: {throttle_time_ms=0,error_code=-1}
2022-08-05T08:37:26,952+0000 [pulsar-ph-kafka-64-30] INFO  io.streamnative.pulsar.handlers.kop.KafkaCommandDecoder - close channel [id: 0xd740cefb, L:/192.168.3.2:9092 ! R:/192.168.3.3:53590] with 0 pending responses
2022-08-05T08:37:26,952+0000 [pulsar-ph-kafka-64-29] INFO  io.streamnative.pulsar.handlers.kop.KafkaCommandDecoder - close channel [id: 0x6e9edb12, L:/192.168.3.2:9092 ! R:/192.168.3.3:53588] with 0 pending responses
2022-08-05T08:37:26,953+0000 [pulsar-ph-kafka-64-29] DEBUG io.streamnative.pulsar.handlers.kop.KafkaRequestHandler - Try to remove all stored groupID on the metadata store. Current connected clientIds: []
2022-08-05T08:37:26,953+0000 [pulsar-ph-kafka-64-30] DEBUG io.streamnative.pulsar.handlers.kop.KafkaRequestHandler - Try to remove all stored groupID on the metadata store. Current connected clientIds: []
```

If there is anything else that you need from me, feel free to let me know. Many thanks.
