### ISSUE TITLE
Flaky-test: KafkaMessageOrderKafkaTest.testKafkaProduceMessageOrder

### ISSUE THREAD

**Issue by Demogorgon314** [streamnative/kop#1444]
KafkaMessageOrderKafkaTest is flaky. The testKafkaProduceMessageOrder test method fails sporadically.

[example failure](https://github.com/streamnative/kop/runs/7738563391?check_suite_focus=true#step:12:207)

```
Error:  testKafkaProduceMessageOrder(io.streamnative.pulsar.handlers.kop.KafkaMessageOrderKafkaTest)  Time elapsed: 0.194 s  <<< FAILURE!
java.lang.AssertionError: expected [0] but found [19]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:652)
	at org.testng.Assert.assertEquals(Assert.java:662)
	at io.streamnative.pulsar.handlers.kop.KafkaMessageOrderTestBase.testKafkaProduceMessageOrder(KafkaMessageOrderTestBase.java:170)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Demogorgon314** [comment]
[Another failure](https://github.com/streamnative/kop/actions/runs/4300612093/jobs/7508758946#step:13:199)
```
Error:  Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 18.47 s <<< FAILURE! - in io.streamnative.pulsar.handlers.kop.KafkaMessageOrderKafkaTest
Error:  testKafkaProduceMessageOrder(io.streamnative.pulsar.handlers.kop.KafkaMessageOrderKafkaTest)  Time elapsed: 2.534 s  <<< FAILURE!
java.lang.AssertionError: expected [2] but found [10]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:652)
	at org.testng.Assert.assertEquals(Assert.java:662)
	at io.streamnative.pulsar.handlers.kop.KafkaMessageOrderTestBase.testKafkaProduceMessageOrder(KafkaMessageOrderTestBase.java:[199](https://github.com/streamnative/kop/actions/runs/4300612093/jobs/7508758946#step:13:200))
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
