### ISSUE TITLE
[BUG] upgrade to kop 2.9.3+   will make kafkaexporter cannot get metrics

### ISSUE THREAD

**Issue by hzluyang** [streamnative/kop#1584]
KOP config:

protocolHandlerDirectory=./protocols
allowAutoTopicCreationType=partitioned
kafkaListeners=PLAINTEXT://10.196.44.30:9092
kafkaAdvertisedListeners=PLAINTEXT://10.196.44.30:9092
brokerEntryMetadataInterceptors=org.apache.pulsar.common.intercept.AppendIndexMetadataInterceptor
brokerDeleteInactiveTopicsEnabled=false
messagingProtocols=kafka
entryFormat=kafka

protocols
1 pulsar-protocol-handler-kafka-2.9.3.1.nar  it's OK 
2 pulsar-protocol-handler-kafka-2.9.3.16.nar it's not OK
3 pulsar-protocol-handler-kafka-2.10.2.1.nar it's not OK

It can be reproduce in standalone mode

kafkaexporter:kafka_exporter-1.6.0:https://github.com/danielqsj/kafka_exporter

when use pulsar-protocol-handler-kafka-2.9.3.1.nar it's OK 
<img width="1701" alt="image" src="https://user-images.githubusercontent.com/14803533/203283614-57f53b8d-1644-4214-8e36-ff8b9043a1cc.png">

when use pulsar-protocol-handler-kafka-2.9.3.16.nar it's not OK
or even upgrade to 2.10.2  it's not OK
<img width="1696" alt="image" src="https://user-images.githubusercontent.com/14803533/203283737-67f1b3ac-2aee-42a2-8f14-cb4d772011cd.png">

I need kafkaexporter to get lag info AND it may not affect kafkaexporter to get metrics IT should alse affect kafka client to consume 

Question:
1 is my KOP config not right?
2 2.9.3+ has a way to get consumergroup lag info

**Comment by BewareMyPower** [comment]
@hzluyang Could you try this NAR file?  https://github.com/streamnative/kop/releases/download/v2.9.3.16/pulsar-protocol-handler-kafka-2.9.3.16-jdk8.nar

I have tested various releases and found that the release from 2.9.3.1 to 2.9.3.5 works but 2.9.3.6 or later doesn't work. We I built 2.9.3.5 in my local env (JDK 17), it also doesn't work. But after I built with JDK 8, it finally works. Therefore, it seems that we need to compile KoP **with JDK 8**.

It might be caused by the environment change of the release CI. Maybe a higher JDK is used since 2.9.3.6 @yaalsn Do you have any idea about it?

----

### How to reproduce

Environment:
- Ubuntu 20.04 (WSL2)
- Java 17.0.4

Run Pulsar 2.9.3 standalone with the following extra configs and a KoP 2.9.3.x release.

```bash
protocolHandlerDirectory=./protocols
allowAutoTopicCreationType=partitioned
kafkaListeners=PLAINTEXT://0.0.0.0:9092
kafkaAdvertisedListeners=PLAINTEXT://127.0.0.1:9092
brokerEntryMetadataInterceptors=org.apache.pulsar.common.intercept.AppendIndexMetadataInterceptor
brokerDeleteInactiveTopicsEnabled=false
messagingProtocols=kafka
entryFormat=kafka
```

Not only kafka_exporter doesn't work, but also basic end to end tests are broken.

```bash
$ ./bin/kafka-console-producer.sh --bootstrap-server localhost:9092 --topic my-topic
>1
[2022-11-24 19:36:31,395] WARN [Producer clientId=console-producer] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2022-11-24 19:36:32,992] WARN [Producer clientId=console-producer] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2022-11-24 19:36:34,597] WARN [Producer clientId=console-producer] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2022-11-24 19:36:36,202] WARN [Producer clientId=console-producer] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
^C[2022-11-24 19:36:38,141] WARN [Producer clientId=console-producer] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
org.apache.kafka.common.KafkaException: Producer closed while send in progress
        at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:909)
        at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:885)
        at kafka.tools.ConsoleProducer$.send(ConsoleProducer.scala:71)
        at kafka.tools.ConsoleProducer$.main(ConsoleProducer.scala:53)
        at kafka.tools.ConsoleProducer.main(ConsoleProducer.scala)
Caused by: org.apache.kafka.common.KafkaException: Requested metadata update after close
```

### Possible cause

After digging into this issue, KoP itself works well, but messages might be pending in the network.

https://github.com/streamnative/kop/blob/e19010d2fb7e06dd40e355bd2d0192ea84db00c7/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaCommandDecoder.java#L446-L454

See the code above, `writeAndFlush` is called for METADATA responses. But these responses were never delivered to the Kafka client, i.e. the listener is never called. So the possible cause might be related to the underlying Netty, but I'm not sure.

### Workaround

If the NAR works, I think we have to build the NAR packages using JDK8. I didn't test branch-2.10. But 2.11 works well with JDK17.

**Comment by Demogorgon314** [comment]
@hzluyang Witch JDK version you used? I guess you used JDK 8, but the KoP NAR is using higher JDK to build, so it might not work when you use JDK 8 to run. You can try to use [pulsar-protocol-handler-kafka-2.9.3.16-jdk8.nar](https://github.com/streamnative/kop/releases/download/v2.9.3.16/pulsar-protocol-handler-kafka-2.9.3.16-jdk8.nar) in JDK 8 env, or you can try to upgrade the JDK version to JDK 11+.

**Comment by BewareMyPower** [comment]
Just correct my comments before. Maybe I was using JDK 8 but I thought I used JDK 17.

```bash
$ echo $JAVA_HOME
/usr/lib/jvm/java-8-openjdk-amd64
$ which java
/usr/bin/java
$ java -version
openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment (build 17.0.4+8-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 17.0.4+8-Ubuntu-120.04, mixed mode, sharing)
```

Because I switched to JDK 8 by changing `JAVA_HOME` env variable to run Pulsar 2.7.5 before. The env variable was not changed back but `java -version` didn't print the actual `java` used by `./bin/pulsar` script.
