### ISSUE TITLE
[BUG] [Transactions] IllegalStateException: WriteTxnMarkerResponse does not contain expected error map for producer id 1128 

### ISSUE THREAD

**Issue by eolivelli** [streamnative/kop#1599]
**Describe the bug**
Under heavy load with OpenMessaging Benchmark (DataStax fork, that has support for Kafka Transactions) I am able to reproduce this error with 100 concurrent transactional producers.
The problem does not reproduce with 20.

```
2022-12-01T11:08:43,513+0000 [nioEventLoopGroup-64-3] INFO io.streamnative.pulsar.handlers.kop.coordinator.transaction.TransactionMarkerChannelManager - Completed sending transactio
n markers for omb-worker-1_37ba3719-c2c7-4395-9359-41bbd586e9b2_tx_9; begin transition to COMPLETE_COMMIT
2022-12-01T11:08:43,490+0000 [nioEventLoopGroup-64-1] ERROR io.streamnative.pulsar.handlers.kop.coordinator.transaction.TransactionMarkerChannelHandler - Transaction marker channel h
andler caught exception.
java.lang.IllegalStateException: WriteTxnMarkerResponse does not contain expected error map for producer id 1128
    at io.streamnative.pulsar.handlers.kop.coordinator.transaction.TransactionMarkerRequestCompletionHandler.lambda$accept$0(TransactionMarkerRequestCompletionHandler.java:66) ~[v0YTMzBwnKJNzZO04yullA/:?]
    at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
    at io.streamnative.pulsar.handlers.kop.coordinator.transaction.TransactionMarkerRequestCompletionHandler.accept(TransactionMarkerRequestCompletionHandler.java:59) ~[v0YTMzBwnKJNzZO04yullA/:?]
    at io.streamnative.pulsar.handlers.kop.coordinator.transaction.TransactionMarkerRequestCompletionHandler.accept(TransactionMarkerRequestCompletionHandler.java:36) ~[v0YTMzBwnKJNzZO04yullA/:?]
    at io.streamnative.pulsar.handlers.kop.coordinator.transaction.PendingRequest.complete(PendingRequest.java:61) ~[v0YTMzBwnKJNzZO04yullA/:?]
    at io.streamnative.pulsar.handlers.kop.coordinator.transaction.TransactionMarkerChannelHandler.channelRead(TransactionMarkerChannelHandler.java:129) ~[v0YTMzBwnKJNzZO04yullA/:?]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[io.netty-netty-transport-4.1.77.Final.jar:4.1.77.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[io.netty-netty-transport-4.1.77.Final.j
```

**Expected behavior**
No error

**Comment by eolivelli** [comment]
there is also this error.

```
2022-12-01T11:08:43,954+0000 [nioEventLoopGroup-64-3] ERROR io.streamnative.pulsar.handlers.kop.coordinator.transaction.TransactionMarkerChannelHandler - Transaction marker channel handler caught exception.
java.lang.IllegalStateException: Transaction metadata's current state is COMPLETE_COMMIT, and its pending state is Optional.empty while trying to remove partitions whose txn marker has been sent, this is not expected
        at io.streamnative.pulsar.handlers.kop.coordinator.transaction.TransactionMetadata.removePartition(TransactionMetadata.java:481) ~[v0YTMzBwnKJNzZO04yullA/:?]
        at io.streamnative.pulsar.handlers.kop.coordinator.transaction.TransactionMarkerRequestCompletionHandler.lambda$hasAbortSendOrRetryPartitions$1(TransactionMarkerRequestCompletionHandler.java:156) ~[v0YTMzBwnKJNzZO04yullA/:?]
        at io.streamnative.pulsar.handlers.kop.utils.CoreUtils.inLock(CoreUtils.java:39) ~[v0YTMzBwnKJNzZO04yullA/:?]
        at io.streamnative.pulsar.handlers.kop.coordinator.transaction.TransactionMetadata.inLock(TransactionMetadata.java:127) ~[v0YTMzBwnKJNzZO04yullA/:?]
        at io.streamnative.pulsar.handlers.kop.coordinator.transaction.TransactionMarkerRequestCompletionHandler.hasAbortSendOrRetryPartitions(TransactionMarkerRequestCompletionHandler.java:150) ~[v0YTMzBwnKJNzZO04yullA/:?]
        at io.streamnative.pulsar.handlers.kop.coordinator.transaction.TransactionMarkerRequestCompletionHandler.tryAddTxnMarker(TransactionMarkerRequestCompletionHandler.java:106) ~[v0YTMzBwnKJNzZO04yullA/:?]
        at io.streamnative.pulsar.handlers.kop.coordinator.transaction.TransactionMarkerRequestCompletionHandler.lambda$accept$0(TransactionMarkerRequestCompletionHandler.java:97) ~[v0YTMzBwnKJNzZO04yullA/:?]
        at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
        at io.streamnative.pulsar.handlers.kop.coordinator.transaction.TransactionMarkerRequestCompletionHandler.accept(TransactionMarkerRequestCompletionHandler.java:59) ~[v0YTMzBwnKJNzZO04yullA/:?]
        at io.streamnative.pulsar.handlers.kop.coordinator.transaction.TransactionMarkerRequestCompletionHandler.accept(TransactionMarkerRequestCompletionHandler.java:36) ~[v0YTMzBwnKJNzZO04yullA/:?]
        at io.streamnative.pulsar.handlers.kop.coordinator.transaction.PendingRequest.complete(PendingRequest.java:61) ~[v0YTMzBwnKJNzZO04yullA/:?]
        at io.streamnative.pulsar.handlers.kop.coordinator.transaction.TransactionMarkerChannelHandler.channelRead(TransactionMarkerChannelHandler.java:129) ~[v0YTMzBwnKJNzZO04yullA/:?]

```

**Comment by eolivelli** [comment]
I am looking into this problem.
