### ISSUE TITLE
[BUG] NullPointerException in PendingTopicFutures.addListener

### ISSUE THREAD

**Issue by eolivelli** [streamnative/kop#1629]
**Describe the bug**

I have seen this error:

11:46:34.696 [pulsar-ph-kafka-63-7:io.streamnative.pulsar.handlers.kop.storage.PartitionLog@491] ERROR io.streamnative.pulsar.handlers.kop.storage.PartitionLog - Failed to handle produce request for kopKafkaProducePulsarConsumeMessageOrder-250-0
java.lang.NullPointerException: null
	at io.streamnative.pulsar.handlers.kop.PendingTopicFutures.addListener(PendingTopicFutures.java:74) ~[classes/:?]
	at io.streamnative.pulsar.handlers.kop.storage.PartitionLog.appendRecords(PartitionLog.java:489) ~[classes/:?]
	at io.streamnative.pulsar.handlers.kop.storage.ReplicaManager.lambda$appendRecords$3(ReplicaManager.java:165) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.storage.ReplicaManager.lambda$appendRecords$4(ReplicaManager.java:164) ~[classes/:?]
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.storage.ReplicaManager.appendRecords(ReplicaManager.java:156) ~[classes/:?]
	at io.streamnative.pulsar.handlers.kop.KafkaRequestHandler.lambda$handleProduceRequest$39(KafkaRequestHandler.java:875) ~[classes/:?]
	at io.streamnative.pulsar.handlers.kop.KafkaRequestHandler.lambda$handleProduceRequest$40(KafkaRequestHandler.java:933) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) [?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) [?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) [?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**To Reproduce**
Not consistently reproducible

**Expected behavior**
No errors

**Additional context**
the addListener method is not properly handling concurrent access, it is possible that 2 threads enter the method and find that the count is greater that 0 but currentTopicFuture is still null.

instead of using "if (count.compareAndSet(0, 1)) {" you should use "accumulateAndGet" and leverage the internal lock of the counter.

**Comment by eolivelli** [comment]
I have seen this in some KSQLDB environment today

2023-01-23T14:12:02,879+0000 [pulsar-ph-kafka-77-8] ERROR io.streamnative.pulsar.handlers.kop.storage.PartitionLog - Failed to handle write request for PAGEVIEWS_JSON-0 origin Client
java.lang.NullPointerException: null
	at io.streamnative.pulsar.handlers.kop.PendingTopicFutures.addListener(PendingTopicFutures.java:74) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.storage.PartitionLog.appendRecords(PartitionLog.java:500) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.storage.ReplicaManager.lambda$appendRecords$3(ReplicaManager.java:176) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.storage.ReplicaManager.lambda$appendRecords$5(ReplicaManager.java:175) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.storage.ReplicaManager.appendRecords(ReplicaManager.java:167) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.KafkaRequestHandler.lambda$handleProduceRequest$40(KafkaRequestHandler.java:884) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.KafkaRequestHandler.lambda$handleProduceRequest$41(KafkaRequestHandler.java:941) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[io.netty-netty-common-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[io.netty-netty-common-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty-netty-common-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[io.netty-netty-transport-classes-epoll-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[io.netty-netty-common-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty-netty-common-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty-netty-common-4.1.86.Final.jar:4.1.86.Final]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
2023-01-23T14:12:02,887+0000 [pulsar-ph-kafka-77-8] ERROR io.streamnative.pulsar.handlers.kop.storage.ReplicaManager - Internal error while handling append to persistent://public/kafka/PAGEVIEWS_JSON-partition-0
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:743) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.storage.ReplicaManager.lambda$appendRecords$3(ReplicaManager.java:177) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.storage.ReplicaManager.lambda$appendRecords$5(ReplicaManager.java:175) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.storage.ReplicaManager.appendRecords(ReplicaManager.java:167) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.KafkaRequestHandler.lambda$handleProduceRequest$40(KafkaRequestHandler.java:884) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.KafkaRequestHandler.lambda$handleProduceRequest$41(KafkaRequestHandler.java:941) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[io.netty-netty-common-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[io.netty-netty-common-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty-netty-common-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[io.netty-netty-transport-classes-epoll-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[io.netty-netty-common-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty-netty-common-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty-netty-common-4.1.86.Final.jar:4.1.86.Final]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.NullPointerException
	at io.streamnative.pulsar.handlers.kop.PendingTopicFutures.addListener(PendingTopicFutures.java:74) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.storage.PartitionLog.appendRecords(PartitionLog.java:500) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.storage.ReplicaManager.lambda$appendRecords$3(ReplicaManager.java:176) ~[?:?]
	... 19 more
