### ISSUE TITLE
[BUG] The server reported an error while monitoring delayed data:MetadataStoreException$BadVersionException

### ISSUE THREAD

**Issue by sikangliu** [streamnative/kop#1796]
**Describe the bug**
When monitoring the kop lag data with kafka-lag-exporter, sometimes the indicators aren't being collected, and pulsar broker is reporting the following error messages:

> 2023-03-30 16:39:26.0189 [metadata-store-72-1] WARN  io.streamnative.pulsar.handlers.kop.KafkaRequestHandler - Store groupId failed, the groupId might already stored.
java.util.concurrent.CompletionException: org.apache.pulsar.metadata.api.MetadataStoreException$BadVersionException: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /client_group_id/10.xx.xx.xx-lag-admin-client-id
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_192]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_192]
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593) ~[?:1.8.0_192]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_192]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_192]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_192]
        at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$null$20(ZKMetadataStore.java:282) ~[org.apache.pulsar-pulsar-metadata-2.9.2.jar:2.9.2]
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870) ~[?:1.8.0_192]
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852) ~[?:1.8.0_192]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_192]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_192]
        at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$null$17(ZKMetadataStore.java:261) ~[org.apache.pulsar-pulsar-metadata-2.9.2.jar:2.9.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.74.Final.jar:4.1.74.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: org.apache.pulsar.metadata.api.MetadataStoreException$BadVersionException: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /client_group_id/10.xx.xx.xx-lag-admin-client-id
        at org.apache.pulsar.metadata.impl.ZKMetadataStore.getException(ZKMetadataStore.java:345) ~[org.apache.pulsar-pulsar-metadata-2.9.2.jar:2.9.2]
        ... 5 more
Caused by: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /client_group_id/10.xx.xx.xx-lag-admin-client-id
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:122) ~[org.apache.zookeeper-zookeeper-3.6.3.jar:3.6.3]
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:54) ~[org.apache.zookeeper-zookeeper-3.6.3.jar:3.6.3]
        at org.apache.pulsar.metadata.impl.ZKMetadataStore.getException(ZKMetadataStore.java:341) ~[org.apache.pulsar-pulsar-metadata-2.9.2.jar:2.9.2]
        ... 5 more
org.apache.pulsar-pulsar-metadata-2.9.2.jar

**Comment by BewareMyPower** [comment]
It seems that this Z-node was not cleared correctly. You can configure `kopEnableGroupLevelConsumerMetrics=false` as a workaround. Or you can delete the Z-node manually and see what will happen.

**Comment by sikangliu** [comment]
> It seems that this Z-node was not cleared correctly. You can configure `kopEnableGroupLevelConsumerMetrics=false` as a workaround. Or you can delete the Z-node manually and see what will happen.

We need to monitor consumer groups of data and traffic delays, so you need to set up kopEnableGroupLevelConsumerMetrics = true

**Comment by sikangliu** [comment]
When viewing z-node, there are no nodes under client_group_id

> WATCHER::
> 
> WatchedEvent state:SyncConnected type:None path:null
> [zk: xxx:2182(CONNECTED) 0] ls /
> [shancha, zookeeper]
> [zk: xxx:2182(CONNECTED) 1] ls /shancha
> [admin, bookies, client_group_id, counters, kop_latest_producer_id_block, ledgers, loadbalance, managed-ledgers, namespace, pulsar, schemas, stream]
> [zk: xxx:2182(CONNECTED) 2] ls /shancha/client_group_id
> []

**Comment by sikangliu** [comment]
When using kafka-lag-exporter to monitor delayed data, updating exporter's version to add the number of retries can resolve this issue
