### ISSUE TITLE
[BUG]Unable to consume messages Kafka-Client versions 2.3.x & above: Consumers terminated/closed with Errors: protocol.types.SchemaException: Error reading field 'topics': java.nio.BufferUnderflowException

### ISSUE THREAD

**Issue by Saswatibhoi** [streamnative/kop#180]
**Describe the bug**
Whenever we are trying to consume from a KoP topic using kafka-clients 2.3.x and above, it just hangs for minutes and then throws the below error. We are able to consume fine from kafka-client versions 2.2.2 and below.
---
[2020-09-15 15:59:16,799] ERROR Error processing message, terminating consumer process:  (kafka.tools.ConsoleConsumer$)
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'topics': java.nio.BufferUnderflowException
        at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:118)
        at org.apache.kafka.common.protocol.ApiKeys.parseResponse(ApiKeys.java:325)
        at org.apache.kafka.clients.NetworkClient.parseStructMaybeUpdateThrottleTimeMetrics(NetworkClient.java:720)
        at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:834)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:553)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:265)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:236)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1301)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1237)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1210)
        at kafka.tools.ConsoleConsumer$ConsumerWrapper.receive(ConsoleConsumer.scala:438)
        at kafka.tools.ConsoleConsumer$.process(ConsoleConsumer.scala:104)
        at kafka.tools.ConsoleConsumer$.run(ConsoleConsumer.scala:78)
        at kafka.tools.ConsoleConsumer$.main(ConsoleConsumer.scala:55)
        at kafka.tools.ConsoleConsumer.main(ConsoleConsumer.scala)
[2020-09-15 15:59:16,799] ERROR [Consumer clientId=x.x.x, groupId=x.x.x] Heartbeat thread failed due to unexpected error (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
java.lang.IllegalStateException: Correlation id for response (334) does not match request (335), request header: RequestHeader(apiKey=HEARTBEAT, apiVersion=2, clientId=x.x.x, correlationId=335)
        at org.apache.kafka.clients.NetworkClient.correlate(NetworkClient.java:945)
        at org.apache.kafka.clients.NetworkClient.parseStructMaybeUpdateThrottleTimeMetrics(NetworkClient.java:721)
        at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:834)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:553)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:265)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:306)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$HeartbeatThread.run(AbstractCoordinator.java:1321)
Processed a total of 0 messages

**To Reproduce**
1. On kafka-clients 2.3.x and above, using the command bin/kafka-console-consumer.sh --bootstrap-server [pulsar-broker-address]:9092 --topic test --from-beginning
2. Consumer connects for the first time and we are successfully able to consume.
3. Disconnect the consumer.
4. Reconnect the consumer with the same group id. :  bin/kafka-console-consumer.sh --bootstrap-server [pulsar-broker-address]:9092 --topic test --group xxx
5. It hangs there for 15-20 minutes and the above error occurs.

Note: We have tested this with both exclusive and shared subscription types.

**Expected behavior**
KoP should support kafka-client versions 2.3.x and above while consuming as well. It just supports only producing messages at the moment for all versions of kafka.

**Additional context**
Mentioning @wmccarley as he is looking into this issue at the moment.
@ptirupac-tibco this is for your reference.

**Comment by ptirupac-tibco** [comment]
Against which version of **KoP** is this?

Asking as #176 resolved Kafka-Client-2.4.x and above issue. Don't think there was an official KoP release since that change.

You'd be able to build off the **_master_** which is up-to date.

**Comment by Saswatibhoi** [comment]
@ptirupac-tibco 

We are using the KoP that is build off the up-to-date master which has the #176 fix. 

We are able to produce fine using Kafka-client-2.3.x and above. The issue we are facing is while consuming.

**Comment by ptirupac-tibco** [comment]
Having issues replicating the error following your steps from the description.

**_Versions Used:_**
- Apache Pulsar - 2.6.1
- Kafka-Console-Consumer - 2.6.0
- KoP - Latest built from **_master_**

`./kafka-console-consumer.sh --bootstrap-server 127.0.0.1:9092 --topic test --group tibco`

And as suggested:
- Consumed few messages
- Killed the consumer
- Reconnected console-consumer using the same **_group-id_** 

I was able to consume messages even after killing & restarting the consumer(with the same group-id) few times.

Attaching the [broker.conf](https://github.com/streamnative/kop/files/5228772/broker.txt) file I used to start my **_Pulsar+KoP_** broker.

_Note: As in #177 I had these specific configurations set. Not sure if it's playing a role here as well._

> brokerDeleteInactiveTopicsEnabled=false
> allowAutoTopicCreationType=partitioned
> allowAutoTopicCreation=true

**Comment by Saswatibhoi** [comment]
I have tried re-testing this scenario with the below configs,

Kafka Version 2.6.0, Pulsar Version: 2.6.0, KoP Latest from master ----> Consumer connects and consumes fine for the first time. When I disconnect the consumer, wait for few minutes, then ty re-connecting using the same group id, it just sits there hung and throws the error message (mentioned earlier)after 20-30 minutes. When I try connecting using a different group id, the again it connects only for the first time, but the same happens when re-connecting the 2nd time.

Kafka Version 2.5.1, Pulsar Version: 2.6.0, KoP Latest from master ----> Same as above.

Kafka Version 2.4.1, Pulsar Version: 2.6.0, KoP Latest from master -----> Same as above.

Kafka Version 2.3.1, Pulsar Version: 2.6.0, KoP Latest from master -----> Same as above.

Kafka Version 2.2.2, Pulsar Version: 2.6.0, KoP Latest from master -----> Every time I disconnect the consumer and try re-connecting using the same group id, it connects immediately and starts consuming fine. I don't see any issues at all consuming using this and the lower version of kafka client version.

The broker configs we are using is as below,

brokerDeleteInactiveTopicsEnabled=false
allowAutoTopicCreationType=non-partitioned
allowAutoTopicCreation=false

We pre-create all our producers and consumers under public/default before connecting.

Any help resolving this issue is highly appreciated.

**Comment by jiazhai** [comment]
@BewareMyPower  Would you please also take a look at this issue if @ptirupac-tibco is busy?

**Comment by BewareMyPower** [comment]
@jiazhai Ok

**Comment by BewareMyPower** [comment]
It's a little hard to reproduce, but I accidentally find the similar logs in CI tests:

```
[INFO] Running io.streamnative.pulsar.handlers.kop.SaslPlainTest
Error:  Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 10.251 s <<< FAILURE! - in io.streamnative.pulsar.handlers.kop.SaslPlainTest
Error:  simpleProduceAndConsume(io.streamnative.pulsar.handlers.kop.SaslPlainTest)  Time elapsed: 0.327 s  <<< FAILURE!
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'brokers': Error reading array of size 65535, only 19 bytes available
	at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:77)
	at org.apache.kafka.common.protocol.ApiKeys.parseResponse(ApiKeys.java:294)
	at org.apache.kafka.clients.NetworkClient.parseStructMaybeUpdateThrottleTimeMetrics(NetworkClient.java:637)
	at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:757)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:519)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:271)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:218)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:230)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:314)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1218)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1175)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1154)
	at io.streamnative.pulsar.handlers.kop.SaslPlainTest.simpleProduceAndConsume(SaslPlainTest.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

While the Kafka client version is 2.0.0.

**Comment by ptirupac-tibco** [comment]
Sorry, missed the messages on this thread.

@BewareMyPower, can you share the steps you had followed to replicate the issue? Even the CI steps would come in handy. I remember having issues trying to replicate it earlier.

**Comment by BewareMyPower** [comment]
@ptirupac-tibco I cannot reproduce it now. I was just trying to fix another issue, accidentally to see the CI tests failed with the similar exception stack. As you see, just the `io.streamnative.pulsar.handlers.kop.SaslPlainTest`. But in most cases this unit test succeed.

**Comment by BewareMyPower** [comment]
I've found the similar issue in another flaky test when consumer calls `poll`:

```
[ERROR] testOffsetCommittedBacklogCleared(io.streamnative.pulsar.handlers.kop.CommitOffsetBacklogTest)  Time elapsed: 3.934 s  <<< FAILURE!
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'brokers': Error reading array of size 65535, only 19 bytes available
	at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:77)
	at org.apache.kafka.common.protocol.ApiKeys.parseResponse(ApiKeys.java:294)
	at org.apache.kafka.clients.NetworkClient.parseStructMaybeUpdateThrottleTimeMetrics(NetworkClient.java:637)
	at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:757)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:519)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:271)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:218)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:230)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:314)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1218)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1175)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1154)
	at io.streamnative.pulsar.handlers.kop.CommitOffsetBacklogTest.testOffsetCommittedBacklogCleared(CommitOffsetBacklogTest.java:195)
```

The root cause may be that the received record's length field is somehow wrong. Here the tests failed because the length field is `[ff ff]`, but it should be 19 here.

The `BufferUnderflowException` is caused by the same reason, i.e. consumer try to read N bytes, when the remain bytes is less than N.

**Comment by mukundrd** [comment]
Facing same, steps to reproduce:

1. Start Zookeeper
2. Start Kafka Server
3. Start Kafka Consumer
```bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic message_topic --from-beginning```
4. Kill Consumer
5. Start Consumer again to listen to same group
```bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic message_topic --from-beginning```
6. Enjoy the Stack Trace:
```
Mukunds-MacBook-Pro:kafka mukundrd$bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic message_topic --from-beginning
[2021-02-21 13:18:10,778] ERROR Error processing message, terminating consumer process:  (kafka.tools.ConsoleConsumer$)
java.nio.BufferUnderflowException
	at java.base/java.nio.Buffer.nextGetIndex(Buffer.java:650)
	at java.base/java.nio.HeapByteBuffer.getInt(HeapByteBuffer.java:391)
	at org.apache.kafka.common.protocol.ByteBufferAccessor.readInt(ByteBufferAccessor.java:43)
	at org.apache.kafka.common.message.ResponseHeaderData.read(ResponseHeaderData.java:97)
	at org.apache.kafka.common.message.ResponseHeaderData.<init>(ResponseHeaderData.java:69)
	at org.apache.kafka.common.requests.ResponseHeader.parse(ResponseHeader.java:66)
	at org.apache.kafka.clients.NetworkClient.parseStructMaybeUpdateThrottleTimeMetrics(NetworkClient.java:740)
	at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:878)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:570)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:265)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:236)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1292)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1233)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1206)
	at kafka.tools.ConsoleConsumer$ConsumerWrapper.receive(ConsoleConsumer.scala:444)
	at kafka.tools.ConsoleConsumer$.process(ConsoleConsumer.scala:103)
	at kafka.tools.ConsoleConsumer$.run(ConsoleConsumer.scala:77)
	at kafka.tools.ConsoleConsumer$.main(ConsoleConsumer.scala:54)
	at kafka.tools.ConsoleConsumer.main(ConsoleConsumer.scala)
[2021-02-21 13:18:10,792] ERROR [Consumer clientId=consumer-console-consumer-97279-1, groupId=console-consumer-97279] Failed to close coordinator (org.apache.kafka.clients.consumer.KafkaConsumer)
java.lang.IllegalStateException: There are no in-flight requests for node 0
	at org.apache.kafka.clients.InFlightRequests.requestQueue(InFlightRequests.java:62)
	at org.apache.kafka.clients.InFlightRequests.completeNext(InFlightRequests.java:70)
	at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:877)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:570)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:265)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:306)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.maybeLeaveGroup(AbstractCoordinator.java:1037)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.close(AbstractCoordinator.java:1001)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.close(ConsumerCoordinator.java:900)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2371)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2338)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2288)
	at kafka.tools.ConsoleConsumer$ConsumerWrapper.cleanup(ConsoleConsumer.scala:458)
	at kafka.tools.ConsoleConsumer$.run(ConsoleConsumer.scala:79)
	at kafka.tools.ConsoleConsumer$.main(ConsoleConsumer.scala:54)
	at kafka.tools.ConsoleConsumer.main(ConsoleConsumer.scala)
[2021-02-21 13:18:12,806] ERROR Unknown error when running consumer:  (kafka.tools.ConsoleConsumer$)
org.apache.kafka.common.KafkaException: Failed to close kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2390)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2338)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2288)
	at kafka.tools.ConsoleConsumer$ConsumerWrapper.cleanup(ConsoleConsumer.scala:458)
	at kafka.tools.ConsoleConsumer$.run(ConsoleConsumer.scala:79)
	at kafka.tools.ConsoleConsumer$.main(ConsoleConsumer.scala:54)
	at kafka.tools.ConsoleConsumer.main(ConsoleConsumer.scala)
Caused by: java.lang.IllegalStateException: There are no in-flight requests for node 0
	at org.apache.kafka.clients.InFlightRequests.requestQueue(InFlightRequests.java:62)
	at org.apache.kafka.clients.InFlightRequests.completeNext(InFlightRequests.java:70)
	at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:877)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:570)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:265)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:306)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.maybeLeaveGroup(AbstractCoordinator.java:1037)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.close(AbstractCoordinator.java:1001)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.close(ConsumerCoordinator.java:900)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2371)
	... 6 more
```

**Comment by mukundrd** [comment]
Kafka Config Values
```KafkaConfig values: 
	advertised.host.name = null
	advertised.listeners = null
	advertised.port = null
	alter.config.policy.class.name = null
	alter.log.dirs.replication.quota.window.num = 11
	alter.log.dirs.replication.quota.window.size.seconds = 1
	authorizer.class.name = 
	auto.create.topics.enable = true
	auto.leader.rebalance.enable = true
	background.threads = 10
	broker.id = 0
	broker.id.generation.enable = true
	broker.rack = null
	client.quota.callback.class = null
	compression.type = producer
	connection.failed.authentication.delay.ms = 100
	connections.max.idle.ms = 600000
	connections.max.reauth.ms = 0
	control.plane.listener.name = null
	controlled.shutdown.enable = true
	controlled.shutdown.max.retries = 3
	controlled.shutdown.retry.backoff.ms = 5000
	controller.quota.window.num = 11
	controller.quota.window.size.seconds = 1
	controller.socket.timeout.ms = 30000
	create.topic.policy.class.name = null
	default.replication.factor = 1
	delegation.token.expiry.check.interval.ms = 3600000
	delegation.token.expiry.time.ms = 86400000
	delegation.token.master.key = null
	delegation.token.max.lifetime.ms = 604800000
	delete.records.purgatory.purge.interval.requests = 1
	delete.topic.enable = true
	fetch.max.bytes = 57671680
	fetch.purgatory.purge.interval.requests = 1000
	group.initial.rebalance.delay.ms = 0
	group.max.session.timeout.ms = 1800000
	group.max.size = 2147483647
	group.min.session.timeout.ms = 6000
	host.name = 
	inter.broker.listener.name = null
	inter.broker.protocol.version = 2.7-IV2
	kafka.metrics.polling.interval.secs = 10
	kafka.metrics.reporters = []
	leader.imbalance.check.interval.seconds = 300
	leader.imbalance.per.broker.percentage = 10
	listener.security.protocol.map = PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
	listeners = null
	log.cleaner.backoff.ms = 15000
	log.cleaner.dedupe.buffer.size = 134217728
	log.cleaner.delete.retention.ms = 86400000
	log.cleaner.enable = true
	log.cleaner.io.buffer.load.factor = 0.9
	log.cleaner.io.buffer.size = 524288
	log.cleaner.io.max.bytes.per.second = 1.7976931348623157E308
	log.cleaner.max.compaction.lag.ms = 9223372036854775807
	log.cleaner.min.cleanable.ratio = 0.5
	log.cleaner.min.compaction.lag.ms = 0
	log.cleaner.threads = 1
	log.cleanup.policy = [delete]
	log.dir = /tmp/kafka-logs
	log.dirs = /tmp/kafka-logs
	log.flush.interval.messages = 9223372036854775807
	log.flush.interval.ms = null
	log.flush.offset.checkpoint.interval.ms = 60000
	log.flush.scheduler.interval.ms = 9223372036854775807
	log.flush.start.offset.checkpoint.interval.ms = 60000
	log.index.interval.bytes = 4096
	log.index.size.max.bytes = 10485760
	log.message.downconversion.enable = true
	log.message.format.version = 2.7-IV2
	log.message.timestamp.difference.max.ms = 9223372036854775807
	log.message.timestamp.type = CreateTime
	log.preallocate = false
	log.retention.bytes = -1
	log.retention.check.interval.ms = 300000
	log.retention.hours = 168
	log.retention.minutes = null
	log.retention.ms = null
	log.roll.hours = 168
	log.roll.jitter.hours = 0
	log.roll.jitter.ms = null
	log.roll.ms = null
	log.segment.bytes = 1073741824
	log.segment.delete.delay.ms = 60000
	max.connection.creation.rate = 2147483647
	max.connections = 2147483647
	max.connections.per.ip = 2147483647
	max.connections.per.ip.overrides = 
	max.incremental.fetch.session.cache.slots = 1000
	message.max.bytes = 1048588
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	min.insync.replicas = 1
	num.io.threads = 8
	num.network.threads = 3
	num.partitions = 1
	num.recovery.threads.per.data.dir = 1
	num.replica.alter.log.dirs.threads = null
	num.replica.fetchers = 1
	offset.metadata.max.bytes = 4096
	offsets.commit.required.acks = -1
	offsets.commit.timeout.ms = 5000
	offsets.load.buffer.size = 5242880
	offsets.retention.check.interval.ms = 600000
	offsets.retention.minutes = 10080
	offsets.topic.compression.codec = 0
	offsets.topic.num.partitions = 50
	offsets.topic.replication.factor = 1
	offsets.topic.segment.bytes = 104857600
	password.encoder.cipher.algorithm = AES/CBC/PKCS5Padding
	password.encoder.iterations = 4096
	password.encoder.key.length = 128
	password.encoder.keyfactory.algorithm = null
	password.encoder.old.secret = null
	password.encoder.secret = null
	port = 9092
	principal.builder.class = null
	producer.purgatory.purge.interval.requests = 1000
	queued.max.request.bytes = -1
	queued.max.requests = 500
	quota.consumer.default = 9223372036854775807
	quota.producer.default = 9223372036854775807
	quota.window.num = 11
	quota.window.size.seconds = 1
	replica.fetch.backoff.ms = 1000
	replica.fetch.max.bytes = 1048576
	replica.fetch.min.bytes = 1
	replica.fetch.response.max.bytes = 10485760
	replica.fetch.wait.max.ms = 500
	replica.high.watermark.checkpoint.interval.ms = 5000
	replica.lag.time.max.ms = 30000
	replica.selector.class = null
	replica.socket.receive.buffer.bytes = 65536
	replica.socket.timeout.ms = 30000
	replication.quota.window.num = 11
	replication.quota.window.size.seconds = 1
	request.timeout.ms = 30000
	reserved.broker.max.id = 1000
	sasl.client.callback.handler.class = null
	sasl.enabled.mechanisms = [GSSAPI]
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.principal.to.local.rules = [DEFAULT]
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism.inter.broker.protocol = GSSAPI
	sasl.server.callback.handler.class = null
	security.inter.broker.protocol = PLAINTEXT
	security.providers = null
	socket.connection.setup.timeout.max.ms = 127000
	socket.connection.setup.timeout.ms = 10000
	socket.receive.buffer.bytes = 102400
	socket.request.max.bytes = 104857600
	socket.send.buffer.bytes = 102400
	ssl.cipher.suites = []
	ssl.client.auth = none
	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
	ssl.endpoint.identification.algorithm = https
	ssl.engine.factory.class = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.certificate.chain = null
	ssl.keystore.key = null
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.principal.mapping.rules = DEFAULT
	ssl.protocol = TLSv1.3
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.certificates = null
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	transaction.abort.timed.out.transaction.cleanup.interval.ms = 10000
	transaction.max.timeout.ms = 900000
	transaction.remove.expired.transaction.cleanup.interval.ms = 3600000
	transaction.state.log.load.buffer.size = 5242880
	transaction.state.log.min.isr = 1
	transaction.state.log.num.partitions = 50
	transaction.state.log.replication.factor = 1
	transaction.state.log.segment.bytes = 104857600
	transactional.id.expiration.ms = 604800000
	unclean.leader.election.enable = false
	zookeeper.clientCnxnSocket = null
	zookeeper.connect = localhost:2181
	zookeeper.connection.timeout.ms = 18000
	zookeeper.max.in.flight.requests = 10
	zookeeper.session.timeout.ms = 18000
	zookeeper.set.acl = false
	zookeeper.ssl.cipher.suites = null
	zookeeper.ssl.client.enable = false
	zookeeper.ssl.crl.enable = false
	zookeeper.ssl.enabled.protocols = null
	zookeeper.ssl.endpoint.identification.algorithm = HTTPS
	zookeeper.ssl.keystore.location = null
	zookeeper.ssl.keystore.password = null
	zookeeper.ssl.keystore.type = null
	zookeeper.ssl.ocsp.enable = false
	zookeeper.ssl.protocol = TLSv1.2
	zookeeper.ssl.truststore.location = null
	zookeeper.ssl.truststore.password = null
	zookeeper.ssl.truststore.type = null
	zookeeper.sync.time.ms = 2000
```

**Comment by BewareMyPower** [comment]
@mukundrd Which version of KoP did you use? And is it a problem with Kafka client 2.3+ or any version of Kafka client?

**Comment by mukundrd** [comment]
@BewareMyPower, I am seeing this on 2.6+ version of Kafka Client.

**Comment by BewareMyPower** [comment]
@mukundrd OK, I'll try to reproduce it later.

**Comment by SanchitSharma28mar** [comment]
@BewareMyPower Getting the same issue as @mukundrd is facing. I am using 2.7 version. Any update on this?

**Comment by BewareMyPower** [comment]
@mukundrd @SanchitSharma28mar 

Sorry for the late response. But I still cannot reproduce in my own environment with following artifacts:
- Pulsar 2.7.0
- KoP 2.7.0.8
- kafka_2.13-2.7.0

1. Deploy a Pulsar standalone with KoP. The extra config items in `conf/standalone.conf` are:
```properties
messagingProtocols=kafka
listeners=PLAINTEXT://127.0.0.1:9092
advertisedAddress=127.0.0.1
allowAutoTopicCreationType=partitioned
```
2. Start a Kafka console consumer
```bash
$ bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic message_topic --from-beginning
```
3. Start a Kafka console producer and enter some messages
```bash
$ ./bin/kafka-console-producer.sh --bootstrap-server localhost:9092 --topic message_topic
>hello
>world
```
4. We can see the console consumer consumed these messages, and just kill it.
```bash
bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic message_topic --from-beginning
hello
world
^CProcessed a total of 2 messages
```
5.  Start the console consumer again like Step 2, and enter new messages in console producer, I didn't find any error and the consumer worked well.

> For the first step, It's a little tricky because KoP cannot run with Pulsar standalone directly. We need to run Pulsar standalone without KoP first. After it's set up, kill the standalone and change the `conf/standalone.conf`. Then start the Pulsar standalone.

Here're the results in my terminals
<img width="964" alt="截屏2021-03-13 下午10 31 22" src="https://user-images.githubusercontent.com/18204803/111033381-f2737a80-844b-11eb-87a4-6d16a51e921b.png">
<img width="1069" alt="截屏2021-03-13 下午10 31 30" src="https://user-images.githubusercontent.com/18204803/111033387-f6070180-844b-11eb-926a-78f1fd0ca149.png">

**Comment by SanchitSharma28mar** [comment]
@BewareMyPower  No problem! I could solve this problem by adding advertisedAddress=127.0.0.1

**Comment by Sushil21** [comment]
I also solved by adding below in server.properties:

advertised.listeners=PLAINTEXT://127.0.0.1:9092
listener=PLAINTEXT://127.0.0.1:9092
