### ISSUE TITLE
[BUG] Pulsar standalone failed to start without any existed data

### ISSUE THREAD

**Issue by BewareMyPower** [streamnative/kop#185]
**Describe the bug**
The first time to run Pulsar standalone would fail.

**To Reproduce**
- KoP 0.3.0
- Pulsar 2.6.1

1. Download [apache-pulsar-2.6.1.tar.gz](https://www.apache.org/dyn/mirrors/mirrors.cgi?action=download&filename=pulsar/pulsar-2.6.1/apache-pulsar-2.6.1-bin.tar.gz) and uncompress it
2. Modify `conf/standalone.conf`:
    ```properties
    protocolHandlerDirectory=./protocols
    messagingProtocols=kafka
    allowAutoTopicCreationType=partitioned
    listeners=PLAINTEXT://127.0.0.1:9092
    advertisedAddress=127.0.0.1
    ```
3. Run `./bin/pulsar-daemon start standalone`
4. The Pulsar standalone failed and exit with following log:

```
[main] ERROR io.streamnative.pulsar.handlers.kop.KafkaProtocolHandler - initGroupCoordinator failed with
org.apache.pulsar.broker.PulsarServerException$NotFoundException: Configured cluster does not exist
    at io.streamnative.pulsar.handlers.kop.utils.MetadataUtils.createKafkaMetadataIfMissing(MetadataUtils.java:82) ~[?:?]
    at io.streamnative.pulsar.handlers.kop.KafkaProtocolHandler.initGroupCoordinator(KafkaProtocolHandler.java:312) ~[?:?]
```

However, if we start the standalone with the default config, i.e. no messaging protocol was specified. Then stop the standalone, modify the config as step 2 above, start, it worked.

Seems that when the KoP called `initGroupCoordinator`, the admin couldn't found the cluster info:

```java
    public static void createKafkaMetadataIfMissing(PulsarAdmin pulsarAdmin, KafkaServiceConfiguration conf)
        throws PulsarServerException, PulsarAdminException {
        String cluster = conf.getClusterName();
        /* ... */

        try {
            Clusters clusters = pulsarAdmin.clusters();
            if (!clusters.getClusters().contains(cluster)) {
                throw new PulsarServerException.NotFoundException("Configured cluster does not exist");
            } else {
                /* ... */
            }
```

But if the standalone started while the metadata of cluster already existed, the cluster could be found.

**Expected behavior**
Pulsar standalone can start without any existed data

**Additional context**
I also tried AoP, the behavior didn't happen, it might be KoP's problem.

KoP 0.2.0 with Pulsar 2.5.0 also works well.

**Comment by BewareMyPower** [comment]
It looks like that AoP doesn't use `PulsarAdmin`, so things are different.

From the debugging, the `pulsarAdmin` cannot get any clusters or tenants after it's created, see 

```java
    @Override
    public void start(BrokerService service) {
        brokerService = service;
        log.info("Starting KafkaProtocolHandler, kop version is: '{}'", KopVersion.getVersion());
        /* other logs... */

        // init and start group coordinator
        if (kafkaConfig.isEnableGroupCoordinator()) {
            try {
                initGroupCoordinator(brokerService);
                /* ... */
            } catch (Exception e) {
                log.error("initGroupCoordinator failed with", e);
            }
        }
    }
```

```java
    public void initGroupCoordinator(BrokerService service) throws Exception {
        GroupConfig groupConfig = /* ... */

        OffsetConfig offsetConfig = /* ... */

        PulsarAdmin pulsarAdmin = service.pulsar().getAdminClient();
        MetadataUtils.createKafkaMetadataIfMissing(pulsarAdmin, kafkaConfig);
```

```java
    public static void createKafkaMetadataIfMissing(PulsarAdmin pulsarAdmin, KafkaServiceConfiguration conf)
        throws PulsarServerException, PulsarAdminException {
        /* pulsarAdmin.clusters().getClusters() or pulsarAdmin.tenants().getTenants() both return a empty list */
```

The logs with more details:

```
/* 1. HTTP service started */
23:57:52.107 [main] INFO  org.apache.pulsar.broker.web.WebService - HTTP Service started at http://0.0.0.0:8080
23:57:52.107 [main] INFO  org.apache.pulsar.broker.web.WebService - HTTPS Service disabled
23:57:52.119 [main] INFO  org.apache.pulsar.broker.loadbalance.LeaderElectionService - LeaderElectionService started
23:57:52.123 [main] INFO  org.apache.pulsar.broker.loadbalance.LeaderElectionService - Broker [http://127.0.0.1:8080] is the leader now, notifying the listener...
23:57:52.130 [ForkJoinPool.commonPool-worker-2] INFO  org.apache.pulsar.broker.cache.LocalZooKeeperCacheService - Successfully created local policies for /admin/local-policies/pulsar/standalone/127.0.0.1:8080 -- Optional.empty
23:57:52.137 [main] INFO  org.apache.pulsar.broker.namespace.OwnershipCache - Trying to acquire ownership of pulsar/standalone/127.0.0.1:8080/0x00000000_0xffffffff
23:57:52.149 [pulsar-ordered-OrderedExecutor-4-0-EventThread] INFO  org.apache.pulsar.broker.namespace.OwnershipCache - Successfully acquired ownership of /namespace/pulsar/standalone/127.0.0.1:8080/0x00000000_0xffffffff
23:57:52.149 [pulsar-30-1] INFO  org.apache.pulsar.broker.PulsarService - Loading all topics on bundle: pulsar/standalone/127.0.0.1:8080/0x00000000_0xffffffff
23:57:52.149 [main] INFO  org.apache.pulsar.broker.namespace.NamespaceService - added heartbeat namespace name in local cache: ns=pulsar/standalone/127.0.0.1:8080
23:57:52.162 [main] INFO  org.apache.pulsar.broker.PulsarService - Starting load management service ...
/* 2. Broker calls ProtocolHandler.start() */
23:57:52.180 [main] INFO  io.streamnative.pulsar.handlers.kop.KafkaProtocolHandler - Starting KafkaProtocolHandler, kop version is: '0.3.1-SNAPSHOT'
```

Not sure if it's the issue of pulsar 2.6.1.

**Comment by BewareMyPower** [comment]
I think it's an issue of pulsar 2.6.1 standalone, when I start zookeeper, bookie, broker step by step, KoP will be loaded successfully.

**Comment by BewareMyPower** [comment]
I've confirmed again it's an issue with Pulsar standalone but not sure when it was introduced.

Add the additional lines in `PulsarService.java`:

```diff
diff --git a/pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java b/pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
index 44048b78cf3..d605cb978b1 100644
--- a/pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
+++ b/pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
@@ -609,6 +609,9 @@ public class PulsarService implements AutoCloseable {
             // to be done only when the broker is fully operative.
             this.startLoadManagementService();
 
+            List<String> clusters = getAdminClient().clusters().getClusters();
+            System.out.println("cluster size: " + clusters.size());
+
             // Initialize the message protocol handlers.
             // start the protocol handlers only after the broker is ready,
             // so that the protocol handlers can access broker service properly.
```

Then debug `PulsarStandaloneStarter --config conf/standalone.conf` with IDE:

<img width="1141" alt="截屏2020-12-24 下午10 28 24" src="https://user-images.githubusercontent.com/18204803/103094097-61a0b600-4637-11eb-9d42-048603383f59.png">

We can see when the protocol handler starts, the `PulsarAdmin` cannot get any clusters, so KoP fails at https://github.com/streamnative/kop/blob/e675b173ece66c41039a1be5d8d9f31d120cedf6/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MetadataUtils.java#L80-L82

From `PulsarStandalone.java` we can see the cluster is created after `PulsarService` starts:

```java
    PulsarService broker;
```

```java
        // Start Broker
        broker = new PulsarService(/* ... */);
        broker.start();

        if (config.isTransactionCoordinatorEnabled()) {
            broker.getTransactionMetadataStoreService().addTransactionMetadataStore(TransactionCoordinatorID.get(0));
        }

        final String cluster = config.getClusterName();

        if (!config.isTlsEnabled()) {
            /* ... */
            createSampleNameSpace(clusterData, cluster);
        } else {
```

**Comment by BewareMyPower** [comment]
When I debug with KoP 0.2.0, the Pulsar standalone could get the clusters before `broker.start()`:

<img width="1098" alt="截屏2020-12-24 下午11 17 53" src="https://user-images.githubusercontent.com/18204803/103096275-5ef58f00-463e-11eb-8e5b-505172183e94.png">

**Comment by BewareMyPower** [comment]
This issue may be caused by #168 . The tests I've done before may have something wrong.

**Comment by jiazhai** [comment]
before 168, it will create the clusters if not exists
