### ISSUE TITLE
Flaky-test: KafkaNonPartitionedTopicTest.testNonPartitionedTopic

### ISSUE THREAD

**Issue by BewareMyPower** [streamnative/kop#1852]
`KafkaNonPartitionedTopicTest` is flaky. The `testNonPartitionedTopic` test method fails sporadically.

[example failure](https://github.com/streamnative/kop/actions/runs/4998819574/jobs/8961726389?pr=1851)

```
Error:  testNonPartitionedTopic(io.streamnative.pulsar.handlers.kop.KafkaNonPartitionedTopicTest)  Time elapsed: 1.464 s  <<< FAILURE!
org.apache.pulsar.client.admin.PulsarAdminException$PreconditionFailedException: Topic has 1 connected producers/consumers
	at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:236)
	at org.apache.pulsar.client.admin.internal.BaseResource$3.failed(BaseResource.java:184)
	at org.glassfish.jersey.client.JerseyInvocation$1.failed(JerseyInvocation.java:882)
	at org.glassfish.jersey.client.JerseyInvocation$1.completed(JerseyInvocation.java:863)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:[229](https://github.com/streamnative/kop/actions/runs/4998819574/jobs/8961726389?pr=1851#step:13:230))
	at org.glassfish.jersey.client.ClientRuntime.access$200(ClientRuntime.java:62)
	at org.glassfish.jersey.client.ClientRuntime$2.lambda$response$0(ClientRuntime.java:173)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
```

**Comment by BewareMyPower** [comment]
For branch-2.9.5, I pushed a commit (fd67cca) directly to ignore this test for now.
