### ISSUE TITLE
Flaky-test: io.streamnative.pulsar.handlers.kop.coordinator.CompactedPartitionedTopicTest.testClose

### ISSUE THREAD

**Issue by Demogorgon314** [streamnative/kop#1900]
`io.streamnative.pulsar.handlers.kop.coordinator.CompactedPartitionedTopicTest` is flaky. The `testClose` test method fails sporadically.

[example failure](https://github.com/streamnative/kop/actions/runs/5253920511/jobs/9491868493#step:14:197)

```
io.streamnative.pulsar.handlers.kop.coordinator.CompactedPartitionedTopicTest
Error:  testClose(io.streamnative.pulsar.handlers.kop.coordinator.CompactedPartitionedTopicTest)  Time elapsed: 1.136 s  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at io.streamnative.pulsar.handlers.kop.coordinator.CompactedPartitionedTopicTest.testClose(CompactedPartitionedTopicTest.java:152)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by BewareMyPower** [comment]
Yeah, there is another possible failure that the future of `close` didn't complete in 30 seconds. 

> Method io.streamnative.pulsar.handlers.kop.coordinator.CompactedPartitionedTopicTest.testClose() didn't finish within the time-out 30000

I assigned this issue to myself.

**Comment by BewareMyPower** [comment]
Another possible failure:

> java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException$BrokerMetadataException: The subscription reader-38dea9adc7 of the topic persistent://public/default/test-close-1686732376355-partition-0 gets the last message id was failed
{"errorMsg":"Consumer not found","reqId":2461281464679433208, "remote":"localhost/127.0.0.1:15002", "local":"/127.0.0.1:54894"}
