### ISSUE TITLE
[BUG] testBrokerRespectsPartitionsOrderAndSizeLimits is flaky

### ISSUE THREAD

**Issue by BewareMyPower** [streamnative/kop#246]
**Describe the bug**
Sometimes `testBrokerRespectsPartitionsOrderAndSizeLimits` may fail like

```
Error:  testBrokerRespectsPartitionsOrderAndSizeLimits(io.streamnative.pulsar.handlers.kop.KafkaApisTest)  Time elapsed: 2.08 s  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
        /* ... */
	at io.streamnative.pulsar.handlers.kop.KafkaApisTest.testBrokerRespectsPartitionsOrderAndSizeLimits(KafkaApisTest.java:550)
```

which is rarely seen in local environment.

In local environment, it could fail with

```
java.lang.AssertionError: expected [29] but found [30]
Expected :29
Actual   :30

	at io.streamnative.pulsar.handlers.kop.KafkaApisTest.checkFetchResponse(KafkaApisTest.java:364)
	at io.streamnative.pulsar.handlers.kop.KafkaApisTest.testBrokerRespectsPartitionsOrderAndSizeLimits(KafkaApisTest.java:591)
```

The expected integer could also be 28 or other number. I've run it in my local environment for 10 times, only succeed for 3 times.

**To Reproduce**
Run `testBrokerRespectsPartitionsOrderAndSizeLimits`.

**Expected behavior**
The test should not fail.

**Comment by BewareMyPower** [comment]
Sometimes some configs need changes, for example:

- #213 changed `maxPartitionBytes` from 190 to 900
- #280 changed `numberTopics` from 5 to 8
