### ISSUE TITLE
[BUG] High CPU usage caused by validateRecords method

### ISSUE THREAD

**Issue by BewareMyPower** [streamnative/kop#446]
**Describe the bug**

I ran `top -H` command to see the `pulsar-io-28-12` thread used a lot of CPU.

```
   PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                                              
 40015 root      20   0 18.662g 9.304g  31192 R 88.9  7.8   3:15.47 pulsar-io-28-12  
```

Then from the `jstack` info I found it's caused by `validateRecords`:

```
"pulsar-io-28-12" #284 prio=5 os_prio=0 cpu=181558.61ms elapsed=2412.46s tid=0x00007f4f6405a0a0 nid=0x9c4f runnable  [0x00007f4ec2148000]
   java.lang.Thread.State: RUNNABLE
        at io.streamnative.pulsar.handlers.kop.KafkaRequestHandler.validateRecords(KafkaRequestHandler.java:1836)
        at io.streamnative.pulsar.handlers.kop.KafkaRequestHandler.handleProduceRequest(KafkaRequestHandler.java:652)
        at io.streamnative.pulsar.handlers.kop.KafkaCommandDecoder.channelRead(KafkaCommandDecoder.java:188)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(java.base@11.0.10/Thread.java:834)
```

**To Reproduce**

**Expected behavior**
`validateRecords` method should not use a lot of CPU here.

**Screenshots**
The CPU usage
![image](https://user-images.githubusercontent.com/18204803/115329301-b529a780-a1c4-11eb-9e2a-351d01b8042f.png)

**Comment by BewareMyPower** [comment]
BTW, I found there's something wrong with the produce metrics. I tried to simply remove the validate code.

```diff
diff --git a/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java b/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
index 425577c..29edf6c 100644
--- a/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
+++ b/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java
@@ -1832,6 +1832,9 @@ public class KafkaRequestHandler extends KafkaCommandDecoder {
             }
         }
 
+        return records;
+
+        /*
         int validBytesCount = 0;
         for (RecordBatch batch : records.batches()) {
             if (batch.magic() >= RecordBatch.MAGIC_VALUE_V2 && batch.baseOffset() != 0) {
@@ -1859,5 +1862,6 @@ public class KafkaRequestHandler extends KafkaCommandDecoder {
         }
 
         return validRecords;
+         */
     }
 }
```

Here're the produce latency comparison.

![image](https://user-images.githubusercontent.com/18204803/115346599-f3ce5a80-a1e2-11eb-9b5a-d93e85655742.png)

1 broker (with 3 bookies), 1 producer with 200 MB/s throughput. The latency with `validateRecords()` is extremely high. However, from the `kop_server_HANDLE_PRODUCE_REQUEST` metrics, it's still a little high but not so much.

<img width="1623" alt="截屏2021-04-20 下午1 58 51" src="https://user-images.githubusercontent.com/18204803/115346995-73f4c000-a1e3-11eb-8ba1-ddd338cef2d6.png">

**Comment by BewareMyPower** [comment]
The latency difference may be caused by other reasons. From the `HandleProduce` metrics compare, the gap is only 1~2 ms

![image](https://user-images.githubusercontent.com/18204803/116355527-8f3b7d00-a82c-11eb-9ea8-817ca8e830f4.png)
