### ISSUE TITLE
OOME Java heap space

### ISSUE THREAD

**Issue by rec7y33** [streamnative/kop#491]
Hello,
I followed the readme guide and setup both pulsar 2.7.1 and kafka 2.0, but when I try to run the producer command and publish something, I the following error:

`ERROR Uncaught exception in thread 'kafka-producer-network-thread | console-producer': (org.apache.kafka.common.utils.KafkaThread)
java.lang.OutOfMemoryError: Java heap space
        at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
        at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
        at org.apache.kafka.common.memory.MemoryPool$1.tryAllocate(MemoryPool.java:30)
        at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:112)
        at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:335)
        at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:296)
        at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:560)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:496)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:425)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:510)
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:239)
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:163)
        at java.lang.Thread.run(Thread.java:748)
`

Please advice. Thanks

**Comment by BewareMyPower** [comment]
It looks like a client side error. Did you run your client and broker on the same machine?  I suggest you use a JVM monitor tools to watch

Also, could you provide your command? I've also run a KoP with Pulsar standalone in my MacOS laptop, even with 200 MB/s produce rate, no OOM happened.

**Comment by rec7y33** [comment]
yes, i run client and broker on same server

command? I run pulsar using baremetal approach
i run zookeeper, bookie, broker separately :
```
bin/pulsar-daemon start broker
bin/pulsar-daemon start bookie
bin/pulsar-daemon start zookeeper
```

my broker.conf:

`...
# KOP
messagingProtocols=kafka
protocolHandlerDirectory=/home/ubuntu/apache-pulsar/protocols
allowAutoTopicCreationType=partitioned
listeners=PLAINTEXT://192.168.3.1:8080
brokerEntryMetadataInterceptors=org.apache.pulsar.common.intercept.AppendIndexMetadataInterceptor
`

then I get the above error when i try to send anything in after this command:
`kafka_2.11-2.0.0/bin/kafka-console-producer.sh --broker-list 192.168.3.1:8080 --topic test`

**Comment by BewareMyPower** [comment]
Your broker list should be `xxx:9092` instead of `xxx:8080`.

```
kafka_2.11-2.0.0/bin/kafka-console-producer.sh --broker-list 192.168.3.1:9092 --topic test
```

**Comment by rec7y33** [comment]
> Your broker list should be `xxx:9092` instead of `xxx:8080`.
> 
> ```
> kafka_2.11-2.0.0/bin/kafka-console-producer.sh --broker-list 192.168.3.1:9092 --topic test
> ```

Hi, 
with broker list set to xxx:9092:
- the pulsar-admin cli is not working, despite changing conf/client to xxx:9092
- when i try to run kafka-console-producer command, i get this error: ```[2021-05-17 02:05:43,628] WARN [Producer clientId=console-producer] Connection to node -1 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)```

**Comment by BewareMyPower** [comment]
KoP is like a plugin of Pulsar. Pulsar uses 6650 port for Pulsar client and 8080 port for Pulsar admin. You should configure `listeners` using another port like 9092, which is common used in Kafka. Then 9092 port could be used for both Kafka client and Kafka admin.

Could you change your config to

```
listeners=PLAINTEXT://192.168.3.1:9092
```

and try again?

**Comment by BewareMyPower** [comment]
Also you need to configure `advertisedAddress` to be the same as the listeners in 2.7.0

```
advertisedAddress=192.168.3.1
```

**Comment by rec7y33** [comment]
> advertisedAddress=192.168.3.1

Yes, I have done that.

**Comment by rec7y33** [comment]
> KoP is like a plugin of Pulsar. Pulsar uses 6650 port for Pulsar client and 8080 port for Pulsar admin. You should configure `listeners` using another port like 9092, which is common used in Kafka. Then 9092 port could be used for both Kafka client and Kafka admin.
> 
> Could you change your config to
> 
> ```
> listeners=PLAINTEXT://192.168.3.1:9092
> ```
> 
> and try again?

I have done just that, but seems like the kafka configuration affects the pulsar configuration.
I have attached my broker.conf file. Appreciate it if you could help me take a look. Thanks! :)
[broker.txt](https://github.com/streamnative/kop/files/6490797/broker.txt)

**Comment by BewareMyPower** [comment]
Your `listeners` is 

```
listeners=http://192.168.3.1:9092
```

You should configure it like

```
listeners=PLAINTEXT://192.168.3.1:9092
```

like what Kafka did, see https://github.com/streamnative/kop/blob/master/docs/configuration.md#configuration for reference.

BTW it's better to ensure the 9092 port is open by using `netstat` command like `netstat -anpt | grep 9092` on Linux.

**Comment by rec7y33** [comment]
> Your `listeners` is
> 
> ```
> listeners=http://192.168.3.1:9092
> ```
> 
> You should configure it like
> 
> ```
> listeners=PLAINTEXT://192.168.3.1:9092
> ```
> 
> like what Kafka did, see https://github.com/streamnative/kop/blob/master/docs/configuration.md#configuration for reference.
> 
> BTW it's better to ensure the 9092 port is open by using `netstat` command like `netstat -anpt | grep 9092` on Linux.

Yeah, I was messing around with the config and forgot to change it back to PLAINTEXT://
It was the first thing I tried but didnt work.

Right now I have change that back to PLAINTEXT://192.168.3.1:9092 like so:

 ```
 # KOP
 messagingProtocols=kafka
 protocolHandlerDirectory=/home/ubuntu/apache-pulsar/protocols
 allowAutoTopicCreationType=partitioned
 listeners=PLAINTEXT://192.168.3.1:9092
 brokerEntryMetadataInterceptors=org.apache.pulsar.common.intercept.AppendIndexMetadataInterceptor
 ```

but am still getting error : ```[2021-05-17 03:54:03,316] WARN [Producer clientId=console-producer] Connection to node -1 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)```

```sudo netstat -anpt | grep 9092``` returns nothing tho.

**Comment by BewareMyPower** [comment]
Then your KoP didn't start successfully. It's better to provide your logs, see `logs/pulsar-broker-xxx.log`. Also change the `immediateFlush` config in `conf/log4j2.yaml` to true, otherwise the logs may be not complete.

**Comment by rec7y33** [comment]
i see this error in my broker log

```14:27:02.353 [main] ERROR org.apache.pulsar.PulsarBrokerStarter - Failed to start pulsar service.
java.lang.IncompatibleClassChangeError: Found class org.apache.pulsar.client.admin.PulsarAdmin, but interface was expected
        at io.streamnative.pulsar.handlers.kop.utils.MetadataUtils.createKafkaMetadataIfMissing(MetadataUtils.java:98) ~[?:?]
        at io.streamnative.pulsar.handlers.kop.utils.MetadataUtils.createOffsetMetadataIfMissing(MetadataUtils.java:59) ~[?:?]
        at io.streamnative.pulsar.handlers.kop.KafkaProtocolHandler.initGroupCoordinator(KafkaProtocolHandler.java:378) ~[?:?]
        at io.streamnative.pulsar.handlers.kop.KafkaProtocolHandler.start(KafkaProtocolHandler.java:273) ~[?:?]
        at org.apache.pulsar.broker.protocol.ProtocolHandlerWithClassLoader.start(ProtocolHandlerWithClassLoader.java:66) ~[org.apache.pulsar-pulsar-broker-2.7.1.jar:2.7.1]
        at org.apache.pulsar.broker.protocol.ProtocolHandlers.lambda$start$4(ProtocolHandlers.java:141) ~[org.apache.pulsar-pulsar-broker-2.7.1.jar:2.7.1]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_292]
        at org.apache.pulsar.broker.protocol.ProtocolHandlers.start(ProtocolHandlers.java:141) ~[org.apache.pulsar-pulsar-broker-2.7.1.jar:2.7.1]
        at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:602) ~[org.apache.pulsar-pulsar-broker-2.7.1.jar:2.7.1]
        at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.start(PulsarBrokerStarter.java:281) ~[org.apache.pulsar-pulsar-broker-2.7.1.jar:2.7.1]
        at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:350) [org.apache.pulsar-pulsar-broker-2.7.1.jar:2.7.1]
```

**Comment by BewareMyPower** [comment]
I see you use pulsar 2.7.1, however the master branch is for latest pulsar's branch. Pulsar changed the `PulsarAdmin` from a class to interface recently.

So you can use KoP 2.7.1.x with Pulsar 2.7.1. For master branch, you can try StreamNative's daily release version, like https://github.com/streamnative/pulsar/releases/tag/v2.8.0-rc-202105170246

**Comment by rec7y33** [comment]
weird, I am using `pulsar-protocol-handler-kafka-2.7.1.6-rc-202105101340.nar`

**Comment by rec7y33** [comment]
alright, it seems to be working fine now that i use `pulsar-protocol-handler-kafka-2.7.1.5.nar` Thanks for your help @BewareMyPower :)

**Comment by BewareMyPower** [comment]
BTW, pulsar-protocol-handler-kafka-2.7.1.6-rc-202105101340.nar is just a wrong release, I'll remove it.
