### ISSUE TITLE
[BUG] Golang sarama integeration tests are easily to fail

### ISSUE THREAD

**Issue by BewareMyPower** [streamnative/kop#629]
**Describe the bug**
Golang sarama integeration tests are easily to fail because the container failed to start, it's because the golang-sarama container is fast and might complete quickly and then stop so that `GenericContainer` cannot catch the logs and wait for the specific `starting to produce` or `starting to consume` log.

```
01:53:04.668 [TestNG-method=simpleProduceAndConsume-1:org.testcontainers.containers.GenericContainer@484] ERROR 🐳 [streamnative/kop-test-golang-sarama:latest] - Could not start container
 org.rnorth.ducttape.TimeoutException: Timeout waiting for result with exception
     at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:54) ~[duct-tape-1.0.8.jar:?]
     at org.rnorth.ducttape.unreliables.Unreliables.retryUntilTrue(Unreliables.java:100) ~[duct-tape-1.0.8.jar:?]
     at org.testcontainers.containers.startupcheck.StartupCheckStrategy.waitUntilStartupSuccessful(StartupCheckStrategy.java:35) ~[testcontainers-1.15.1.jar:?]
     at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:432) ~[testcontainers-1.15.1.jar:?]
     at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325) ~[testcontainers-1.15.1.jar:?]
     at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) [duct-tape-1.0.8.jar:?]
     at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323) [testcontainers-1.15.1.jar:?]
     at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311) [testcontainers-1.15.1.jar:?]
     at io.streamnative.pulsar.handlers.kop.KafkaIntegrationTest.simpleProduceAndConsume(KafkaIntegrationTest.java:204) [test-classes/:?]
```

**To Reproduce**
Just run the `KafkaIntegrationTest` in local env or you can see it in CI.

**Expected behavior**
We should find a not flaky way to wait for the container start.

**Screenshots**

**Additional context**

**Comment by BewareMyPower** [comment]
Currently I'll ignore these two tests in https://github.com/streamnative/kop/pull/628
