### ISSUE TITLE
[BUG] Unstable system in a 2 brokers cluster

### ISSUE THREAD

**Issue by eolivelli** [streamnative/kop#661]
**Describe the bug**

After some time on the Pulsar broker I see KOP logging these lines in a loop. The only medicine is to nuke the cluster.

```
11:47:04.432 [pulsar-ordered-OrderedExecutor-7-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - Opening managed ledger public/default/persistent/test2-partition-0
^C11:47:04.433 [bookkeeper-ml-scheduler-OrderedScheduler-4-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [public/default/persistent/test2-partition-0] Closing managed ledger
11:47:04.433 [bookkeeper-ml-scheduler-OrderedScheduler-4-0] ERROR io.streamnative.pulsar.handlers.kop.KafkaTopicManager - [[id: 0x2b5b81b3, L:/127.0.0.1:9093 - R:/127.0.0.1:52452]]Get empty topic for name persistent://public/default/test2-partition-0
11:47:04.433 [bookkeeper-ml-scheduler-OrderedScheduler-4-0] ERROR io.streamnative.pulsar.handlers.kop.KafkaTopicManager - [[id: 0x2b5b81b3, L:/127.0.0.1:9093 - R:/127.0.0.1:52452]] Failed to getTopicConsumerManager caused by getTopic 'persistent://public/default/test2-partition-0' returns empty
```

**To Reproduce**
Start locally a Pulsar cluster with two brokers.
Generate some load on a topic, using KOP
bin/kafka-console-producer.sh --bootstrap-server localhost:19092 --topic test2
bin/kafka-console-consumer.sh --bootstrap-server localhost:19092 --topic test2

Reboot the brokers a couple of times, while producing and consuming the messages....

**Expected behavior**
The system is stable.

**Comment by eolivelli** [comment]
deleting the partitioned topic works as well, connecting to another broker (in the example to localhost:8081)

pulsar-admin --admin-url http://localhost:8081 topics delete-partitioned-topic persistent://public/default/test2

**Comment by eolivelli** [comment]
I am also seeing these errors:
```

org.apache.bookkeeper.mledger.ManagedLedgerException$ManagedLedgerFencedException: java.lang.Exception: Attempted to use a fenced managed ledger
Caused by: java.lang.Exception: Attempted to use a fenced managed ledger
	at org.apache.bookkeeper.mledger.ManagedLedgerException$ManagedLedgerFencedException.<init>(ManagedLedgerException.java:80) ~[org.apache.pulsar-managed-ledger-2.8.0.1.1.3.jar:2.8.0.1.1.3]
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.checkFenced(ManagedLedgerImpl.java:3441) ~[org.apache.pulsar-managed-ledger-2.8.0.1.1.3.jar:2.8.0.1.1.3]
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.newNonDurableCursor(ManagedLedgerImpl.java:1028) ~[org.apache.pulsar-managed-ledger-2.8.0.1.1.3.jar:2.8.0.1.1.3]
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.newNonDurableCursor(ManagedLedgerImpl.java:1020) ~[org.apache.pulsar-managed-ledger-2.8.0.1.1.3.jar:2.8.0.1.1.3]
	at io.streamnative.pulsar.handlers.kop.KafkaTopicConsumerManager.lambda$asyncGetCursorByOffset$7(KafkaTopicConsumerManager.java:237) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616) ~[?:1.8.0_275]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628) ~[?:1.8.0_275]
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996) ~[?:1.8.0_275]
	at io.streamnative.pulsar.handlers.kop.KafkaTopicConsumerManager.asyncGetCursorByOffset(KafkaTopicConsumerManager.java:225) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.KafkaTopicConsumerManager.asyncCreateCursorIfNotExists(KafkaTopicConsumerManager.java:155) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.KafkaTopicConsumerManager.removeCursorFuture(KafkaTopicConsumerManager.java:141) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.MessageFetchContext.lambda$null$5(MessageFetchContext.java:243) ~[?:?]
```

**Comment by eolivelli** [comment]
The problem is due to the fact that the partition had been deleted
this (producing one message) fixes the problem
`pulsar-client produce -m test -n 10 test2`

this looks like a bug in Pulsar, because we are setting "createTopicIfMissing" to `true` (as I have `allowAutoTopicCreation` set to true in my broker.conf)
see here
https://github.com/streamnative/kop/blob/3095d55909985906b358aedca101f38d0af807aa/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KopBrokerLookupManager.java#L126

I wanted to not set `brokerDeleteInactiveTopicsEnabled` to false, but probably that's the only workaround at the moment

probably we should report a better error in the logs

**Comment by BewareMyPower** [comment]
Is this case when partitions were deleted while the metadata still existed? Maybe we can also configure `brokerDeleteInactivePartitionedTopicMetadataEnabled=true` to solve it.

I've also encountered the case that only part of partitions were deleted, but I cannot reproduce it now.

**Comment by eolivelli** [comment]
@BewareMyPower it would be great to not configure that option.
BTW the main problem is that the system is stuck.
We should find a way to create the missing partition.
I'm fact if I run a regular Pulsar producer it is able to fix the topic and then Kafka works again
