### ISSUE TITLE
[BUG] NullPointerException on current Apache Master 2.9.0-SNAPSHOT

### ISSUE THREAD

**Issue by eolivelli** [streamnative/kop#677]
**Describe the bug**
I see this error while trying to run latest KOP on latest Master branch of Pulsar

```
Caused by: java.lang.NullPointerException
	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.getMessage(TypedMessageBuilderImpl.java:287) ~[pulsar-client-original.jar:2.9.0-SNAPSHOT]
	at io.streamnative.pulsar.handlers.kop.format.PulsarEntryFormatter.recordToEntry(PulsarEntryFormatter.java:183) ~[?:?]
	at io.streamnative.pulsar.handlers.kop.format.PulsarEntryFormatter.lambda$null$0(PulsarEntryFormatter.java:65) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_275]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_275]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_275]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_275]
	at java.util.stream.ForEachOps$ForEachOrderedTask.onCompletion(ForEachOps.java:494) ~[?:1.8.0_275]
	at java.util.concurrent.CountedCompleter.tryComplete(CountedCompleter.java:577) ~[?:1.8.0_275]
	at java.util.stream.ForEachOps$ForEachOrderedTask.doCompute(ForEachOps.java:482) ~[?:1.8.0_275]
	at java.util.stream.ForEachOps$ForEachOrderedTask.compute(ForEachOps.java:399) ~[?:1.8.0_275]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_275]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_275]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_275]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_275]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_275]
```

This is because we are setting a "null" Producer in the MessageBuilder
https://github.com/streamnative/kop/blob/4de6212abe7ec7345f88e0c5484aef49ba947af0/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/format/PulsarEntryFormatter.java#L146

Recently the producer is required, in order to get the original topic to which the message is to be sent

**Comment by eolivelli** [comment]
@BewareMyPower  can you please take a look ? I am adding a workaround locally to see KOP working

**Comment by BewareMyPower** [comment]
Okay, I think it's not hard to fix, could you help with this issue? @Demogorgon314
