### ISSUE TITLE
Flaky-test: KafkaTopicConsumerManagerTest.testTopicManagerClose

### ISSUE THREAD

**Issue by Demogorgon314** [streamnative/kop#809]
KafkaTopicConsumerManagerTest is flaky. The testTopicManagerClose test method fails sporadically.

[example failure](https://github.com/streamnative/kop/pull/791/checks?check_run_id=3871605822#step:5:349)

```
Error:  testTopicManagerClose(io.streamnative.pulsar.handlers.kop.KafkaTopicConsumerManagerTest)  Time elapsed: 0.167 s  <<< FAILURE!
java.lang.AssertionError: expected [null] but found [io.streamnative.pulsar.handlers.kop.KafkaTopicConsumerManager@5f6dc36e]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotSame(Assert.java:772)
	at org.testng.Assert.assertNull(Assert.java:708)
	at org.testng.Assert.assertNull(Assert.java:697)
	at io.streamnative.pulsar.handlers.kop.KafkaTopicConsumerManagerTest.testTopicManagerClose(KafkaTopicConsumerManagerTest.java:490)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Demogorgon314** [comment]
[another example failure](https://github.com/streamnative/kop/runs/3892988783?check_suite_focus=true#step:5:323)
